"""The Visio shots harness's own logic: the SVG diff, the builds, the run store. None of it needs Visio."""

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest

TOOL = Path(__file__).resolve().parent.parent / "tools" / "visio_shots.py"


def _tool():
    spec = importlib.util.spec_from_file_location("visio_shots", TOOL)
    module = importlib.util.module_from_spec(spec)
    sys.modules["visio_shots"] = module
    spec.loader.exec_module(module)
    return module


def _svg(name: str, *shapes: str, styles: str = ".st1 {fill:#ffffff;stroke:#000000}\n.st2 {fill:#000000}") -> str:
    """A page as Visio's SVG export writes one: its export comment, a style sheet, and `shapes`."""
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
        f"<!-- Generated by Microsoft Visio, SVG Export {name} Page-1 -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" xmlns:v="http://schemas.microsoft.com/visio/2003/SVGExtensions/"'
        ' viewBox="0 0 595.276 841.89">\n'
        f'<style type="text/css"><![CDATA[\n{styles}\n]]></style>\n'
        '<g v:mID="0" v:groupContext="foregroundPage"><title>Page-1</title>\n' + "\n".join(shapes) + "\n</g></svg>\n"
    )


def _box(shape_id: int, x: float = 18.0, text: str = "Box", text_class: str = "st2") -> str:
    """A shape as Visio's export writes one; its text follows Visio's own `v:` records inside `<text>`, as their tail."""
    return (
        f'<g id="shape{shape_id}-1" v:mID="{shape_id}" v:groupContext="shape" transform="translate({x},-700)">'
        f"<title>Sheet.{shape_id}</title>"
        '<path d="M0 841.89 L72 841.89 L72 800 Z" class="st1"/>'
        f'<text x="20" y="820" class="{text_class}"><v:paragraph v:horizAlign="1"/><v:tabList/>{text}</text>\t\t</g>'
    )


def test_a_change_to_what_a_label_says_is_a_difference():
    tool = _tool()
    [finding] = tool._diff_svgs(_svg("a", _box(1, text="Shape A")), _svg("b", _box(1, text="Shape B")))
    assert '"Shape A"' in finding
    assert '"Shape B"' in finding


def test_the_spaces_a_label_draws_between_its_runs_are_part_of_it():
    """Visio's export sets xml:space="preserve": a space at the end of one run is drawn, between words."""
    tool = _tool()

    def label(first_run: str) -> str:
        return _box(1).replace(
            "<v:tabList/>Box</text>", f'<v:tabList/><tspan class="st2">{first_run}</tspan><tspan class="st2">B</tspan></text>'
        )

    assert len(tool._diff_svgs(_svg("a", label("A ")), _svg("b", label("A")))) == 1


def _arrow(shape_id: int, marker_id: str, arrow_scale: str) -> tuple[str, str]:
    """A connector whose style ends it with a marker, and the `<defs>` that draw the marker, as Visio writes both."""
    defs = (
        '<defs id="Markers"><g id="lend4"><path d="M 2 1 L 0 0 L 2 -1 L 2 1 " style="stroke:none"/></g>'
        f'<marker id="{marker_id}" class="st9" refX="-7.6" orient="auto" markerUnits="strokeWidth" overflow="visible">'
        f'<use xlink:href="#lend4" transform="scale({arrow_scale}) "/></marker></defs>'
    )
    shape = (
        f'<g id="shape{shape_id}-1" v:mID="{shape_id}" v:groupContext="shape" transform="translate(0,-500)">'
        f'<title>Sheet.{shape_id}</title><path d="M0 800 L100 800" class="st3"/></g>'
    )
    return defs, shape


def _svg_with_defs(defs: str, shape: str, marker_id: str) -> str:
    styles = f".st3 {{marker-end:url(#{marker_id});stroke:#5e5e5e}}\n.st9 {{fill:#5e5e5e;stroke:#5e5e5e}}"
    page = _svg("x", shape, styles=styles)
    return page.replace('xmlns:v="', 'xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:v="').replace(
        '<g v:mID="0"', defs + '<g v:mID="0"'
    )


def test_an_arrowhead_drawn_at_another_size_is_the_connectors_difference():
    tool = _tool()
    first = _svg_with_defs(*_arrow(6, "mrkr4-16", "-3.8,-3.8"), "mrkr4-16")
    second = _svg_with_defs(*_arrow(6, "mrkr4-16", "-7.6,-7.6"), "mrkr4-16")
    [finding] = tool._diff_svgs(first, second)
    assert finding.startswith("shape 6 drawn differently: ")
    assert "scale(-7.6,-7.6)" in finding


def test_an_arrowhead_renumbered_by_the_export_is_no_difference():
    tool = _tool()
    first = _svg_with_defs(*_arrow(6, "mrkr4-16", "-3.8,-3.8"), "mrkr4-16")
    second = _svg_with_defs(*_arrow(6, "mrkr4-55", "-3.8,-3.8"), "mrkr4-55")
    assert tool._diff_svgs(first, second) == []


def test_the_same_drawing_exported_under_two_names_has_no_differences():
    tool = _tool()
    assert tool._diff_svgs(_svg("a.open.svg", _box(1)), _svg("a.recalc.svg", _box(1))) == []


def test_normalising_drops_the_file_name_visio_writes_into_the_export():
    tool = _tool()
    assert tool._normalise_svg(_svg("a.open.svg", _box(1))) == tool._normalise_svg(_svg("b.recalc.svg", _box(1)))


def test_a_moved_shape_is_named_with_how_far_it_moved():
    tool = _tool()
    findings = tool._diff_svgs(_svg("a", _box(6, x=173.906)), _svg("b", _box(6, x=101.906)))
    assert findings == ["shape 6 moved (-1.000 in, +0.000 in): translate(173.906,-700) -> translate(101.906,-700)"]


def test_a_class_renumbered_to_the_same_style_is_no_difference():
    tool = _tool()
    first = _svg("a", _box(1, text_class="st2"), styles=".st1 {fill:#ffffff}\n.st2 {fill:#000000}")
    second = _svg("b", _box(1, text_class="st9"), styles=".st1 {fill:#ffffff}\n.st9 {fill:#000000}")
    assert tool._diff_svgs(first, second) == []


def test_a_text_colour_change_is_reported_with_both_styles():
    tool = _tool()
    first = _svg("a", _box(2, text="Text Color", text_class="st2"), styles=".st1 {fill:#ffffff}\n.st2 {fill:#ff0000}")
    second = _svg("b", _box(2, text="Text Color", text_class="st2"), styles=".st1 {fill:#ffffff}\n.st2 {fill:#0000ff}")
    [finding] = tool._diff_svgs(first, second)
    assert finding.startswith("shape 2 drawn differently: ")
    assert "fill:#ff0000" in finding
    assert "fill:#0000ff" in finding


def _text_background(style_class: str) -> str:
    return (
        '<g id="shape5-1" v:mID="5" v:groupContext="shape" transform="translate(0,-504)"><title>Sheet.5</title>'
        f'<rect v:rectContext="textBkgnd" x="60" y="607" width="23" height="8" class="{style_class}"/></g>'
    )


def test_how_a_stroke_that_is_not_drawn_would_be_drawn_is_no_difference():
    """Visio's export gives a text background `stroke:none` with a stroke width on one export and none on the next,
    even for a shape nothing touched; with no stroke, the width draws nothing."""
    tool = _tool()
    first = _svg("a", _text_background("st1"), styles=".st1 {fill:#ffffff;stroke:none;stroke-linecap:butt;stroke-width:7.2}")
    second = _svg("b", _text_background("st1"), styles=".st1 {fill:#ffffff;stroke:none;stroke-linecap:butt}")
    assert tool._diff_svgs(first, second) == []


def test_the_width_of_a_stroke_that_is_drawn_is_a_difference():
    tool = _tool()
    first = _svg("a", _text_background("st1"), styles=".st1 {stroke:#000000;stroke-width:0.75}")
    second = _svg("b", _text_background("st1"), styles=".st1 {stroke:#000000;stroke-width:7.2}")
    assert len(tool._diff_svgs(first, second)) == 1


def _swimlane_frame(style_class: str, width: str = "785.197") -> str:
    """A shape whose frame Visio exports with a class it has hidden, as it does for a swimlane's."""
    return (
        '<g id="shape5-1" v:mID="5" v:groupContext="shape" transform="translate(0,-504)"><title>Sheet.5</title>'
        f'<rect x="0" y="340.157" width="{width}" height="255.118" class="{style_class}"/></g>'
    )


def test_how_a_hidden_element_would_be_drawn_is_no_difference():
    tool = _tool()
    styles = ".st5 {stroke:#d49f00;stroke-width:1.25;visibility:hidden}"
    first = _svg("a", _swimlane_frame("st5", width="785.197"), styles=styles)
    second = _svg("b", _swimlane_frame("st5", width="300"), styles=styles)
    assert tool._diff_svgs(first, second) == []


def test_an_element_hidden_in_one_drawing_and_shown_in_the_other_is_a_difference():
    tool = _tool()
    styles = ".st5 {stroke:#d49f00;visibility:hidden}\n.st6 {stroke:#d49f00}"
    assert (
        len(
            tool._diff_svgs(_svg("a", _swimlane_frame("st5"), styles=styles), _svg("b", _swimlane_frame("st6"), styles=styles))
        )
        == 1
    )


def test_the_colour_of_a_fill_drawn_fully_transparent_is_no_difference():
    tool = _tool()
    first = _svg("a", _swimlane_frame("st4"), styles=".st4 {fill:#fff8f1;fill-opacity:0}")
    second = _svg("b", _swimlane_frame("st4"), styles=".st4 {fill:#000000;fill-opacity:0}")
    assert tool._diff_svgs(first, second) == []


def test_a_shape_taken_out_of_its_group_is_a_difference():
    """Its own transform is relative to the group: out of the group, the same transform draws it somewhere else."""
    tool = _tool()
    member = (
        '<g id="shape4-1" v:mID="4" v:groupContext="shape" transform="translate(0,0)"><title>Sheet.4</title>'
        '<path d="M0 0 L1 1" class="st1"/></g>'
    )
    group_open = '<g id="group3-1" v:mID="3" v:groupContext="group" transform="translate(100,0)"><title>Sheet.3</title>'
    inside = _svg("a", group_open + member + "</g>")
    outside = _svg("b", group_open + "</g>" + member)
    assert tool._diff_svgs(inside, outside) == ["shape 4 regrouped: in shape 3 -> on the page"]


def test_what_visio_records_about_an_element_but_does_not_draw_is_no_difference():
    """`v:langID` is the language Visio spell-checks a label in; no renderer reads it."""
    tool = _tool()
    first = _svg("a", _box(1).replace('<text x="20"', '<text v:langID="1033" x="20"'))
    second = _svg("b", _box(1).replace('<text x="20"', '<text v:langID="2057" x="20"'))
    assert tool._diff_svgs(first, second) == []


def test_the_spaces_inside_a_style_value_are_part_of_it():
    tool = _tool()

    def with_font(family: str) -> str:
        return _svg("x", _box(1), styles=f".st1 {{fill:#ffffff}}\n.st2 {{font-family:{family};  stroke-dasharray : 1 2 }}")

    assert len(tool._diff_svgs(with_font("Segoe UI"), with_font("SegoeUI"))) == 1
    assert (
        tool._diff_svgs(
            with_font("Segoe UI"), with_font("Segoe UI").replace("stroke-dasharray : 1 2", "stroke-dasharray:1  2")
        )
        == []
    )


def test_a_style_the_whole_page_inherits_is_compared():
    """Visio's export sets `font-size:12px` on the root; a label's `em` size is relative to it."""
    tool = _tool()

    def page(size: str) -> str:
        styles = f".st1 {{fill:#ffffff}}\n.st2 {{font-size:1.33em}}\n.st6 {{font-size:{size}}}"
        return _svg("x", _box(1), styles=styles).replace(' viewBox="', ' class="st6" viewBox="')

    [finding] = tool._diff_svgs(page("12px"), page("24px"))
    assert finding.startswith("the page drawn differently: ")
    assert "font-size:24px" in finding


def test_a_shape_only_one_drawing_has_is_reported():
    tool = _tool()
    assert tool._diff_svgs(_svg("a", _box(1)), _svg("b", _box(1), _box(7))) == ["shape 7 only in the second drawing"]


def _group(member_x: float = 0, own_fill_class: str = "st1") -> str:
    """A group as Visio's export writes one: an outer `group` element, its member, then the group's own drawing
    in a `groupContent` element that carries the group's ID again."""
    return (
        '<g id="group1-1" transform="translate(54,-513)" v:mID="1" v:groupContext="group"><title>Sheet.1</title>'
        f'<g id="shape2-2" v:mID="2" v:groupContext="shape" transform="translate({member_x},0)">'
        '<path d="M0 0 L1 1" class="st1"/></g>'
        '<g id="shape1-4" v:mID="1" v:groupContext="groupContent">'
        f'<path d="M0 0 L72 0 L72 72 Z" class="{own_fill_class}"/><text x="4" y="40" class="st2">Shape A</text></g></g>'
    )


def test_a_group_members_change_is_its_own_not_the_groups():
    tool = _tool()
    assert tool._diff_svgs(_svg("a", _group(member_x=0)), _svg("b", _group(member_x=72))) == [
        "shape 2 moved (+1.000 in, +0.000 in): translate(0,0) -> translate(72,0)"
    ]


def test_a_change_to_a_groups_own_drawing_is_the_groups():
    tool = _tool()
    styles = ".st1 {fill:#ffffff}\n.st2 {fill:#000000}\n.st3 {fill:#ff0000}"
    [finding] = tool._diff_svgs(
        _svg("a", _group(own_fill_class="st1"), styles=styles), _svg("b", _group(own_fill_class="st3"), styles=styles)
    )
    assert finding.startswith("shape 1 drawn differently: ")
    assert "fill:#ff0000" in finding


def test_what_the_export_records_but_does_not_draw_is_no_difference():
    """Shape Data, user cells and text blocks ride along in Visio's own namespace; no renderer draws them."""
    tool = _tool()

    def with_property(value: str) -> str:
        return _box(1).replace(
            "<title>Sheet.1</title>",
            f'<title>Sheet.1</title><desc>{value}</desc><v:custProps><v:cp v:nameU="Function" v:val="VT4({value})"/></v:custProps>',
        )

    assert tool._diff_svgs(_svg("a", with_property("Sales")), _svg("b", with_property("Function 1"))) == []


def test_a_page_drawn_at_another_size_is_a_difference():
    tool = _tool()
    first = _svg("a", _box(1))
    second = first.replace('viewBox="0 0 595.276 841.89"', 'viewBox="0 0 841.89 595.276"')
    assert tool._diff_svgs(first, second) == ["the page: viewBox=0 0 595.276 841.89 -> viewBox=0 0 841.89 595.276"]


def test_shapes_stacked_in_another_order_are_a_difference():
    tool = _tool()
    assert tool._diff_svgs(_svg("a", _box(1), _box(2)), _svg("b", _box(2), _box(1))) == [
        "shapes stacked in another order, bottom first: 1, 2 -> 2, 1"
    ]


def test_each_case_is_exported_on_its_first_checked_page_and_recalculates_its_checked_cells(tmp_path):
    tool = _tool()
    expected = {
        "01_a": {"line": "a", "cells": [[2, 5, "PinX", 1.0], [2, 5, "Width", 2.0]], "glue": []},
        "02_b": {"line": "b", "cells": [], "glue": []},
    }
    (tmp_path / "expected.json").write_text(json.dumps(expected), encoding="utf-8")
    cases = tool._read_cases(tmp_path)
    assert [(c.stem, c.page, c.triggers) for c in cases] == [
        ("01_a", 2, ((2, 5, "PinX"), (2, 5, "Width"))),
        ("02_b", 1, ()),
    ]


def test_a_case_checking_cells_on_two_pages_is_exported_page_by_page(tmp_path):
    """Each page a case checks is exported, after every cell it checks has recalculated."""
    tool = _tool()
    expected = {"07_pages": {"line": "p", "cells": [[1, 5, "PinX", 1.0], [2, 9, "PinX", 2.0]], "glue": []}}
    (tmp_path / "expected.json").write_text(json.dumps(expected), encoding="utf-8")
    triggers = ((1, 5, "PinX"), (2, 9, "PinX"))
    assert [(c.stem, c.file_stem, c.page, c.triggers) for c in tool._read_cases(tmp_path)] == [
        ("07_pages/page 1", "07_pages", 1, triggers),
        ("07_pages/page 2", "07_pages", 2, triggers),
    ]


def test_a_page_a_case_checks_glue_on_is_exported_too(tmp_path):
    """A glue check on a page no cell check names was never photographed (#462)."""
    tool = _tool()
    expected = {
        "03_glue": {"line": "g", "cells": [[1, 5, "PinX", 1.0]], "glue": [[2, 6, [[6, "BeginX", 2, "PinX"]]]]},
        "04_only_glue": {"line": "o", "cells": [], "glue": [[3, 6, []]]},
    }
    (tmp_path / "expected.json").write_text(json.dumps(expected), encoding="utf-8")
    assert [(c.stem, c.file_stem, c.page) for c in tool._read_cases(tmp_path)] == [
        ("03_glue/page 1", "03_glue", 1),
        ("03_glue/page 2", "03_glue", 2),
        ("04_only_glue", "04_only_glue", 3),
    ]


def test_a_page_of_a_case_is_never_named_as_another_case_is(tmp_path):
    """A case's stem names a file in one folder, so it holds no ``/``; "x page 2" was free for a builder to use (#462)."""
    tool = _tool()
    expected = {
        "x": {"line": "pages", "cells": [[1, 5, "PinX", 1.0], [2, 5, "PinX", 1.0]], "glue": []},
        "x page 2": {"line": "a stem of its own", "cells": [[1, 5, "PinX", 1.0]], "glue": []},
    }
    (tmp_path / "expected.json").write_text(json.dumps(expected), encoding="utf-8")
    stems = [case.stem for case in tool._read_cases(tmp_path)]
    assert len(set(stems)) == len(stems) == 3


_FAKE_BUILDER = """
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Case:
    line: str
    stem: str


def good(out: Path) -> Case:
    (out / "01_good.txt").write_text("written")  # not a .vsdx: conftest would judge it as a package
    return Case("01_good: fine", "01_good")


def bad(out: Path) -> Case:
    raise AttributeError("'Shape' object has no attribute 'require_id'")


CASES = (good, bad)


def as_json(cases):
    return {case.stem: {"line": case.line, "cells": [], "glue": []} for case in cases}
"""


def _fake_library(root: Path) -> Path:
    src = root / "src"
    (src / "vsdxkit").mkdir(parents=True)
    (src / "vsdxkit" / "__init__.py").write_text("", encoding="utf-8")
    return src


def test_a_case_the_library_cannot_build_is_recorded_and_the_rest_still_build(tmp_path):
    tool = _tool()
    builder = tmp_path / "cases.py"
    builder.write_text(_FAKE_BUILDER, encoding="utf-8")
    out = tmp_path / "out"
    errors = tool._build(builder, _fake_library(tmp_path / "lib"), out)
    assert errors == {"bad": "AttributeError: 'Shape' object has no attribute 'require_id'"}
    assert json.loads((out / "expected.json").read_text(encoding="utf-8")) == {
        "01_good": {"line": "01_good: fine", "cells": [], "glue": []}
    }


def test_a_build_that_would_import_another_copy_of_the_library_is_refused(tmp_path):
    tool = _tool()
    builder = tmp_path / "cases.py"
    builder.write_text(_FAKE_BUILDER, encoding="utf-8")
    empty = tmp_path / "empty-src"
    empty.mkdir()
    with pytest.raises(tool.BuildFailed, match="not the one asked for"):
        tool._build(builder, empty, tmp_path / "out")


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(repo), "-c", "user.name=t", "-c", "user.email=t@example.com", *args],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def test_a_refs_library_is_exported_from_git_without_touching_the_checkout(tmp_path):
    tool = _tool()
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q")
    _fake_library(repo)
    (repo / "src" / "vsdxkit" / "__init__.py").write_text("VERSION = 'ref'\n", encoding="utf-8")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "ref")
    (repo / "src" / "vsdxkit" / "__init__.py").write_text("VERSION = 'working tree'\n", encoding="utf-8")

    src, commit = tool._export_library(repo, "HEAD", tmp_path / "export")

    assert commit == _git(repo, "rev-parse", "HEAD")
    assert (src / "vsdxkit" / "__init__.py").read_text(encoding="utf-8") == "VERSION = 'ref'\n"
    assert (repo / "src" / "vsdxkit" / "__init__.py").read_text(encoding="utf-8") == "VERSION = 'working tree'\n"


def _shots(open_svg: str, recalc_svg: str) -> dict:
    return {"open": {"svg": open_svg, "png": b"png-open"}, "recalc": {"svg": recalc_svg, "png": b"png-recalc"}}


def _run(tool, store: Path, run_id: str, candidate_recalc_x: float):
    """A recorded run of one case: its before, the ref and the candidate, the candidate stale on open."""
    before = _svg("x", _box(1, x=18))
    shots = {
        "before": {"01_a": _shots(before, before)},
        "ref": {"01_a": _shots(before, before)},
        "candidate": {"01_a": _shots(before, _svg("x", _box(1, x=candidate_recalc_x)))},
    }
    identity = {
        "run": run_id,
        "created": "2026-09-27T00:00:00Z",
        "commit": "c" * 40,
        "branch": "test/visio-shots",
        "dirty": False,
        "against": {"ref": "main", "commit": "m" * 40},
        "visio": {"version": "16.0", "build": "1"},
        "dpi": 150,
    }
    lines = {"01_a": "01_a: shape 1 is somewhere"}
    return tool._record_run(store, identity, lines, shots, build_errors={"ref": {}, "candidate": {}})


def test_a_recorded_run_names_the_stale_case_and_stores_each_drawing_once(tmp_path):
    tool = _tool()
    manifest = _run(tool, tmp_path, "r1", candidate_recalc_x=90)

    case = manifest["cases"]["01_a"]
    assert case["stale_on_open"] is True
    assert case["findings"]["candidate on open -> after recalc"][0].startswith("shape 1 moved (+1.000 in")
    # before, the ref and the candidate on open are one drawing; with the
    # candidate after recalc that is two objects, however many runs hold them
    assert len(list((tmp_path / "objects").rglob("*.svg"))) == 2
    assert (tmp_path / "runs" / "r1" / "manifest.json").exists()
    assert "01_a" in (tmp_path / "runs" / "r1" / "summary.md").read_text(encoding="utf-8")
    assert (tmp_path / "local" / "r1" / "report.html").exists()
    [line] = (tmp_path / "index.jsonl").read_text(encoding="utf-8").splitlines()
    assert json.loads(line)["stale_on_open"] == ["01_a"]


def _identity(run_id: str) -> dict:
    return {
        "run": run_id,
        "created": "2026-09-27T00:00:00Z",
        "commit": "c" * 40,
        "branch": "b",
        "dirty": False,
        "against": None,
        "visio": {},
        "dpi": 150,
    }


def test_a_run_whose_every_case_draws_the_same_on_open_and_after_recalc_passes(tmp_path):
    tool = _tool()
    drawing = _svg("x", _box(1))
    manifest = tool._record_run(
        tmp_path,
        _identity("r1"),
        {"01_a": "a"},
        {"candidate": {"01_a": _shots(drawing, drawing)}},
        build_errors={"candidate": {}},
    )
    assert tool._failures(manifest) == []


def test_a_run_fails_when_a_candidate_case_could_not_be_built(tmp_path):
    """A case that never reached Visio was not judged; a run that skipped it has not passed."""
    tool = _tool()
    drawing = _svg("x", _box(1))
    manifest = tool._record_run(
        tmp_path,
        _identity("r1"),
        {"01_a": "a"},
        {"candidate": {"01_a": _shots(drawing, drawing)}},
        build_errors={"candidate": {"glued_end": "AttributeError: no"}},
    )
    assert tool._failures(manifest) == ["the candidate could not build glued_end: AttributeError: no"]


def test_a_run_fails_when_visio_could_not_export_a_candidate_case(tmp_path):
    tool = _tool()
    manifest = tool._record_run(
        tmp_path, _identity("r1"), {"01_a": "a"}, {"candidate": {"01_a": {"error": "file is corrupt"}}}, build_errors={}
    )
    assert tool._failures(manifest) == ["01_a was not judged: Visio could not export it: file is corrupt"]


def test_a_run_fails_when_visio_recalculated_fewer_cells_than_the_case_checks(tmp_path):
    """A shape Visio dropped has no cells to recalculate: its two exports agree only because nothing recalculated."""
    tool = _tool()
    drawing = _svg("x", _box(1))
    shot = _shots(drawing, drawing) | {"triggered": 1, "asked": 3}
    manifest = tool._record_run(tmp_path, _identity("r1"), {"01_a": "a"}, {"candidate": {"01_a": shot}}, build_errors={})
    assert tool._failures(manifest) == ["01_a was not judged: Visio recalculated 1 of the 3 cells it checks"]


def test_a_before_file_may_lack_the_shapes_its_case_creates(tmp_path):
    tool = _tool()
    drawing = _svg("x", _box(1))
    shots = {
        "before": {"01_a": _shots(drawing, drawing) | {"triggered": 1, "asked": 2}},
        "candidate": {"01_a": _shots(drawing, drawing) | {"triggered": 2, "asked": 2}},
    }
    manifest = tool._record_run(tmp_path, _identity("r1"), {"01_a": "a"}, shots, build_errors={})
    assert tool._failures(manifest) == []


def test_every_staged_file_has_a_name_of_its_own():
    """Stems that differ only in a space and an underscore are two cases, not one file."""
    tool = _tool()
    jobs = [
        ("candidate", tool._Case("foo page 1", "a", 1, (), file="foo"), Path("foo.vsdx")),
        ("candidate", tool._Case("foo_page_1", "b", 1, ()), Path("foo_page_1.vsdx")),
    ]
    names = tool._staged_names(jobs)
    assert len(set(names)) == 2


def test_the_refs_cases_are_photographed_with_the_refs_own_shape_ids(tmp_path):
    """The ref's library may give a shape the case creates another ID; its triggers are the ones its own build wrote."""
    tool = _tool()
    candidate = tool._Case("03b", "line", 1, ((1, 9, "Prop.ShapeClass"),))
    ref = tool._Case("03b", "line", 1, ((1, 8, "Prop.ShapeClass"),))
    jobs = tool._jobs(tmp_path / "candidate", [candidate], tmp_path / "ref", {"03b": ref})
    assert [(variant, case.triggers) for variant, case, _path in jobs] == [
        ("ref", ((1, 8, "Prop.ShapeClass"),)),
        ("candidate", ((1, 9, "Prop.ShapeClass"),)),
    ]


def test_two_runs_given_one_id_are_recorded_apart(tmp_path):
    """Two runs of one commit started in the same second must not write into one record."""
    tool = _tool()
    drawing = _svg("x", _box(1))
    shots = {"candidate": {"01_a": _shots(drawing, drawing)}}
    first = tool._record_run(tmp_path, _identity("r1"), {"01_a": "a"}, shots, build_errors={})
    second = tool._record_run(tmp_path, _identity("r1"), {"01_a": "a"}, shots, build_errors={})
    assert (first["run"], second["run"]) == ("r1", "r1-2")
    assert (tmp_path / "runs" / "r1-2" / "manifest.json").exists()
    runs = [json.loads(line)["run"] for line in (tmp_path / "index.jsonl").read_text(encoding="utf-8").splitlines()]
    assert runs == ["r1", "r1-2"]


def test_the_visio_an_export_started_is_read_from_the_file_it_wrote(tmp_path):
    """On a timeout only the Visio the export started may be killed; its ID is in the file the script wrote."""
    tool = _tool()
    written = tmp_path / "visio.pid"
    assert tool._exporter_process_id(written) is None
    written.write_text("", encoding="utf-8")
    assert tool._exporter_process_id(written) is None
    written.write_text("4242\r\n", encoding="utf-8")
    assert tool._exporter_process_id(written) == 4242


def test_the_report_carries_its_images_inside_it(tmp_path):
    tool = _tool()
    _run(tool, tmp_path, "r1", candidate_recalc_x=90)
    report = (tmp_path / "local" / "r1" / "report.html").read_text(encoding="utf-8")
    assert "data:image/png;base64," in report
    assert 'src="http' not in report


def test_diff_runs_lists_the_case_whose_drawing_changed_between_runs(tmp_path):
    tool = _tool()
    _run(tool, tmp_path, "r1", candidate_recalc_x=90)
    _run(tool, tmp_path, "r2", candidate_recalc_x=18)
    lines = tool._diff_runs(tmp_path, "r1", "r2")
    assert lines[0] == "01_a: stale on open in r1, not in r2"
    assert any(line.strip().startswith("after recalc: shape 1 moved (-1.000 in") for line in lines)


def test_diff_runs_of_a_run_with_itself_is_empty(tmp_path):
    tool = _tool()
    _run(tool, tmp_path, "r1", candidate_recalc_x=90)
    assert tool._diff_runs(tmp_path, "r1", "r1") == []


def test_diff_runs_reports_a_case_that_stopped_building(tmp_path):
    """A case whose builder now throws never reaches the cases map; the run's verdict changed all the same."""
    tool = _tool()
    drawing = _svg("x", _box(1))
    shots = {"candidate": {"01_a": _shots(drawing, drawing)}}
    tool._record_run(tmp_path, _identity("r1"), {"01_a": "a"}, shots, build_errors={"candidate": {}})
    tool._record_run(tmp_path, _identity("r2"), {"01_a": "a"}, shots, build_errors={"candidate": {"glued_end": "E"}})
    assert tool._diff_runs(tmp_path, "r1", "r2") == ["fails only in r2: the candidate could not build glued_end: E"]


def test_a_runs_builder_is_named_by_its_content(tmp_path):
    """Two builders at one path are two builders: a run records which one it ran."""
    tool = _tool()
    builder = tmp_path / "cases.py"
    builder.write_text("CASES = ()\n", encoding="utf-8")
    first = tool._builder_identity(builder)
    builder.write_text("CASES = (lambda out: None,)\n", encoding="utf-8")
    second = tool._builder_identity(builder)
    assert first["path"] == second["path"] == str(builder)
    assert first["sha256"] != second["sha256"]


def test_an_unknown_command_is_a_usage_error(capsys):
    tool = _tool()
    with pytest.raises(SystemExit) as exit_info:
        tool.main(["photograph"])
    assert exit_info.value.code == 2


def test_the_exporter_names_its_visio_by_the_process_that_owns_its_window():
    """Visio 16's `Application.ProcessID` names no process: 199300 against a VISIO.EXE of 39524.

    Killing by it missed the exporter's own Visio, and could kill whatever
    process had that ID. The owner of `WindowHandle32` is the VISIO.EXE, and
    is trusted only once it is seen to be one.
    """
    script = (TOOL.parent / "visio_export.ps1").read_text(encoding="utf-8")
    assert "$app.ProcessID" not in script
    assert "GetWindowThreadProcessId" in script
    assert "$process.ProcessName -ne 'VISIO'" in script
