"""The Visio shots harness's own logic: the SVG diff, the builds, the run store. None of it needs Visio."""

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest

TOOL = Path(__file__).resolve().parent.parent / "tools" / "visio_shots.py"


def _tool():
    spec = importlib.util.spec_from_file_location("visio_shots", TOOL)
    module = importlib.util.module_from_spec(spec)
    sys.modules["visio_shots"] = module
    spec.loader.exec_module(module)
    return module


def _svg(name: str, *shapes: str, styles: str = ".st1 {fill:#ffffff;stroke:#000000}\n.st2 {fill:#000000}") -> str:
    """A page as Visio's SVG export writes one: its export comment, a style sheet, and `shapes`."""
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
        f"<!-- Generated by Microsoft Visio, SVG Export {name} Page-1 -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" xmlns:v="http://schemas.microsoft.com/visio/2003/SVGExtensions/"'
        ' viewBox="0 0 595.276 841.89">\n'
        f'<style type="text/css"><![CDATA[\n{styles}\n]]></style>\n'
        '<g v:mID="0" v:groupContext="foregroundPage"><title>Page-1</title>\n' + "\n".join(shapes) + "\n</g></svg>\n"
    )


def _box(shape_id: int, x: float = 18.0, text: str = "Box", text_class: str = "st2") -> str:
    return (
        f'<g id="shape{shape_id}-1" v:mID="{shape_id}" v:groupContext="shape" transform="translate({x},-700)">'
        f"<title>Sheet.{shape_id}</title>"
        '<path d="M0 841.89 L72 841.89 L72 800 Z" class="st1"/>'
        f'<text x="20" y="820" class="{text_class}">{text}</text></g>'
    )


def test_the_same_drawing_exported_under_two_names_has_no_differences():
    tool = _tool()
    assert tool._diff_svgs(_svg("a.open.svg", _box(1)), _svg("a.recalc.svg", _box(1))) == []


def test_normalising_drops_the_file_name_visio_writes_into_the_export():
    tool = _tool()
    assert tool._normalise_svg(_svg("a.open.svg", _box(1))) == tool._normalise_svg(_svg("b.recalc.svg", _box(1)))


def test_a_moved_shape_is_named_with_how_far_it_moved():
    tool = _tool()
    findings = tool._diff_svgs(_svg("a", _box(6, x=173.906)), _svg("b", _box(6, x=101.906)))
    assert findings == ["shape 6 moved (-1.000 in, +0.000 in): translate(173.906,-700) -> translate(101.906,-700)"]


def test_a_class_renumbered_to_the_same_style_is_no_difference():
    tool = _tool()
    first = _svg("a", _box(1, text_class="st2"), styles=".st1 {fill:#ffffff}\n.st2 {fill:#000000}")
    second = _svg("b", _box(1, text_class="st9"), styles=".st1 {fill:#ffffff}\n.st9 {fill:#000000}")
    assert tool._diff_svgs(first, second) == []


def test_a_text_colour_change_is_reported_with_both_styles():
    tool = _tool()
    first = _svg("a", _box(2, text="Text Color", text_class="st2"), styles=".st1 {fill:#ffffff}\n.st2 {fill:#ff0000}")
    second = _svg("b", _box(2, text="Text Color", text_class="st2"), styles=".st1 {fill:#ffffff}\n.st2 {fill:#0000ff}")
    [finding] = tool._diff_svgs(first, second)
    assert finding.startswith("shape 2 drawn differently: ")
    assert "fill:#ff0000" in finding
    assert "fill:#0000ff" in finding


def _text_background(style_class: str) -> str:
    return (
        '<g id="shape5-1" v:mID="5" v:groupContext="shape" transform="translate(0,-504)"><title>Sheet.5</title>'
        f'<rect v:rectContext="textBkgnd" x="60" y="607" width="23" height="8" class="{style_class}"/></g>'
    )


def test_how_a_stroke_that_is_not_drawn_would_be_drawn_is_no_difference():
    """Visio's export gives a text background `stroke:none` with a stroke width on one export and none on the next,
    even for a shape nothing touched; with no stroke, the width draws nothing."""
    tool = _tool()
    first = _svg("a", _text_background("st1"), styles=".st1 {fill:#ffffff;stroke:none;stroke-linecap:butt;stroke-width:7.2}")
    second = _svg("b", _text_background("st1"), styles=".st1 {fill:#ffffff;stroke:none;stroke-linecap:butt}")
    assert tool._diff_svgs(first, second) == []


def test_the_width_of_a_stroke_that_is_drawn_is_a_difference():
    tool = _tool()
    first = _svg("a", _text_background("st1"), styles=".st1 {stroke:#000000;stroke-width:0.75}")
    second = _svg("b", _text_background("st1"), styles=".st1 {stroke:#000000;stroke-width:7.2}")
    assert len(tool._diff_svgs(first, second)) == 1


def test_a_shape_only_one_drawing_has_is_reported():
    tool = _tool()
    assert tool._diff_svgs(_svg("a", _box(1)), _svg("b", _box(1), _box(7))) == ["shape 7 only in the second drawing"]


def test_a_group_members_change_is_its_own_not_the_groups():
    tool = _tool()

    def group(member_x: float) -> str:
        return (
            '<g id="group3" v:mID="3" v:groupContext="shape" transform="translate(10,-10)"><title>Sheet.3</title>'
            f'<g id="shape4" v:mID="4" v:groupContext="groupContent" transform="translate({member_x},0)">'
            '<path d="M0 0 L1 1" class="st1"/></g></g>'
        )

    assert tool._diff_svgs(_svg("a", group(0)), _svg("b", group(72))) == [
        "shape 4 moved (+1.000 in, +0.000 in): translate(0,0) -> translate(72,0)"
    ]


def test_each_case_is_exported_on_its_first_checked_page_and_recalculates_its_checked_cells(tmp_path):
    tool = _tool()
    expected = {
        "01_a": {"line": "a", "cells": [[2, 5, "PinX", 1.0], [2, 5, "Width", 2.0]], "glue": []},
        "02_b": {"line": "b", "cells": [], "glue": []},
    }
    (tmp_path / "expected.json").write_text(json.dumps(expected), encoding="utf-8")
    cases = tool._read_cases(tmp_path)
    assert [(c.stem, c.page, c.triggers) for c in cases] == [
        ("01_a", 2, ((2, 5, "PinX"), (2, 5, "Width"))),
        ("02_b", 1, ()),
    ]


_FAKE_BUILDER = """
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Case:
    line: str
    stem: str


def good(out: Path) -> Case:
    (out / "01_good.txt").write_text("written")  # not a .vsdx: conftest would judge it as a package
    return Case("01_good: fine", "01_good")


def bad(out: Path) -> Case:
    raise AttributeError("'Shape' object has no attribute 'require_id'")


CASES = (good, bad)


def as_json(cases):
    return {case.stem: {"line": case.line, "cells": [], "glue": []} for case in cases}
"""


def _fake_library(root: Path) -> Path:
    src = root / "src"
    (src / "vsdxkit").mkdir(parents=True)
    (src / "vsdxkit" / "__init__.py").write_text("", encoding="utf-8")
    return src


def test_a_case_the_library_cannot_build_is_recorded_and_the_rest_still_build(tmp_path):
    tool = _tool()
    builder = tmp_path / "cases.py"
    builder.write_text(_FAKE_BUILDER, encoding="utf-8")
    out = tmp_path / "out"
    errors = tool._build(builder, _fake_library(tmp_path / "lib"), out)
    assert errors == {"bad": "AttributeError: 'Shape' object has no attribute 'require_id'"}
    assert json.loads((out / "expected.json").read_text(encoding="utf-8")) == {
        "01_good": {"line": "01_good: fine", "cells": [], "glue": []}
    }


def test_a_build_that_would_import_another_copy_of_the_library_is_refused(tmp_path):
    tool = _tool()
    builder = tmp_path / "cases.py"
    builder.write_text(_FAKE_BUILDER, encoding="utf-8")
    empty = tmp_path / "empty-src"
    empty.mkdir()
    with pytest.raises(tool.BuildFailed, match="not the one asked for"):
        tool._build(builder, empty, tmp_path / "out")


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(repo), "-c", "user.name=t", "-c", "user.email=t@example.com", *args],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def test_a_refs_library_is_exported_from_git_without_touching_the_checkout(tmp_path):
    tool = _tool()
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q")
    _fake_library(repo)
    (repo / "src" / "vsdxkit" / "__init__.py").write_text("VERSION = 'ref'\n", encoding="utf-8")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "ref")
    (repo / "src" / "vsdxkit" / "__init__.py").write_text("VERSION = 'working tree'\n", encoding="utf-8")

    src, commit = tool._export_library(repo, "HEAD", tmp_path / "export")

    assert commit == _git(repo, "rev-parse", "HEAD")
    assert (src / "vsdxkit" / "__init__.py").read_text(encoding="utf-8") == "VERSION = 'ref'\n"
    assert (repo / "src" / "vsdxkit" / "__init__.py").read_text(encoding="utf-8") == "VERSION = 'working tree'\n"


def _shots(open_svg: str, recalc_svg: str) -> dict:
    return {"open": {"svg": open_svg, "png": b"png-open"}, "recalc": {"svg": recalc_svg, "png": b"png-recalc"}}


def _run(tool, store: Path, run_id: str, candidate_recalc_x: float):
    """A recorded run of one case: its before, the ref and the candidate, the candidate stale on open."""
    before = _svg("x", _box(1, x=18))
    shots = {
        "before": {"01_a": _shots(before, before)},
        "ref": {"01_a": _shots(before, before)},
        "candidate": {"01_a": _shots(before, _svg("x", _box(1, x=candidate_recalc_x)))},
    }
    identity = {
        "run": run_id,
        "created": "2026-09-27T00:00:00Z",
        "commit": "c" * 40,
        "branch": "test/visio-shots",
        "dirty": False,
        "against": {"ref": "main", "commit": "m" * 40},
        "visio": {"version": "16.0", "build": "1"},
        "dpi": 150,
    }
    lines = {"01_a": "01_a: shape 1 is somewhere"}
    return tool._record_run(store, identity, lines, shots, build_errors={"ref": {}, "candidate": {}})


def test_a_recorded_run_names_the_stale_case_and_stores_each_drawing_once(tmp_path):
    tool = _tool()
    manifest = _run(tool, tmp_path, "r1", candidate_recalc_x=90)

    case = manifest["cases"]["01_a"]
    assert case["stale_on_open"] is True
    assert case["findings"]["candidate on open -> after recalc"][0].startswith("shape 1 moved (+1.000 in")
    # before, the ref and the candidate on open are one drawing; with the
    # candidate after recalc that is two objects, however many runs hold them
    assert len(list((tmp_path / "objects").rglob("*.svg"))) == 2
    assert (tmp_path / "runs" / "r1" / "manifest.json").exists()
    assert "01_a" in (tmp_path / "runs" / "r1" / "summary.md").read_text(encoding="utf-8")
    assert (tmp_path / "local" / "r1" / "report.html").exists()
    [line] = (tmp_path / "index.jsonl").read_text(encoding="utf-8").splitlines()
    assert json.loads(line)["stale_on_open"] == ["01_a"]


def test_the_report_carries_its_images_inside_it(tmp_path):
    tool = _tool()
    _run(tool, tmp_path, "r1", candidate_recalc_x=90)
    report = (tmp_path / "local" / "r1" / "report.html").read_text(encoding="utf-8")
    assert "data:image/png;base64," in report
    assert 'src="http' not in report


def test_diff_runs_lists_the_case_whose_drawing_changed_between_runs(tmp_path):
    tool = _tool()
    _run(tool, tmp_path, "r1", candidate_recalc_x=90)
    _run(tool, tmp_path, "r2", candidate_recalc_x=18)
    lines = tool._diff_runs(tmp_path, "r1", "r2")
    assert lines[0] == "01_a: stale on open in r1, not in r2"
    assert any(line.strip().startswith("after recalc: shape 1 moved (-1.000 in") for line in lines)


def test_diff_runs_of_a_run_with_itself_is_empty(tmp_path):
    tool = _tool()
    _run(tool, tmp_path, "r1", candidate_recalc_x=90)
    assert tool._diff_runs(tmp_path, "r1", "r1") == []


def test_an_unknown_command_is_a_usage_error(capsys):
    tool = _tool()
    with pytest.raises(SystemExit) as exit_info:
        tool.main(["photograph"])
    assert exit_info.value.code == 2
