"""Photograph what Visio draws for a case set, compare it, and keep a record of every run.

Usage:
    python tools/visio_shots.py run [--against REF] [--builder PATH] [--store DIR] [--dpi N]
    python tools/visio_shots.py diff-runs <run-a> <run-b> [--store DIR]

``run`` builds the case set twice when ``--against`` names a git ref: once
with this working tree's library (the candidate) and once with that ref's,
exported with ``git archive`` (the ref). The builder is
``tools/writes_land_cases.py`` unless ``--builder`` names another module that
keeps its contract: ``CASES``, callables that each write one case into a
folder and return it, and ``as_json``, which turns them into
``expected.json``. A case the ref's library cannot build is recorded, and
the rest still run.

A Windows Visio (``tools/visio_export.ps1``) exports each case's page as PNG
and SVG as it opens, then again after ``Cell.Trigger()`` recalculates every
cell the case checks. It does this for the candidate, the ref and the
untouched fixture (``<case>.before.vsdx``). The SVG names each shape by its
Visio ID and carries its position, path, text and style, so two exports are
compared shape by shape, exactly. No pixels are compared and no text is
recognised.

Visio draws from the values a file caches, so a candidate drawn differently
after recalculating was stale on open: the file said one thing and would
show another as soon as anything recalculated (#461). ``run`` exits 1 when
any case is, and when any candidate case was never judged because it could
not be built or exported. Differences from the ref or from the fixture are what the
change did, and are reported, not judged.

Every run is recorded in the store (``.hermes/visio-shots`` by default):
``runs/<run>/manifest.json`` and ``summary.md``, each SVG once under
``objects/`` by its hash, and one line in ``index.jsonl``. All of that is
text and is committed. The PNGs and a self-contained ``report.html`` go under
``local/``, which git ignores. ``diff-runs`` lists the cases whose candidate
drawing or verdict changed between two recorded runs.
"""

from __future__ import annotations

import argparse
import base64
import datetime
import hashlib
import html
import io
import itertools
import json
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from xml.etree import ElementTree

_REPO = Path(__file__).resolve().parent.parent
_TOOLS = _REPO / "tools"
_STORE = _REPO / ".hermes" / "visio-shots"
_BUILDER = _TOOLS / "writes_land_cases.py"

_VARIANTS = ("before", "ref", "candidate")
"""The columns of every comparison: the untouched fixture, the ref's build, this tree's build."""
_STATES = ("open", "recalc")
"""When each export is taken: as the file opens, and after the checked cells recalculate."""
_STATE_WORDS = {"open": "on open", "recalc": "after recalc"}

_SVG_NS = "{http://www.w3.org/2000/svg}"
_VISIO_NS = "{http://schemas.microsoft.com/visio/2003/SVGExtensions/}"
_XLINK_NS = "{http://www.w3.org/1999/xlink}"
_POINTS_PER_INCH = 72.0
_CLIP = 240
"""The longest a drawn part is quoted in a finding; a path's `d` can run to kilobytes."""

_STALE = "candidate on open -> after recalc"
_REF_STATES = "ref on open -> after recalc"
_REF_TO_CANDIDATE = "ref -> candidate, after recalc"
_BEFORE_TO_CANDIDATE = "before -> candidate, after recalc"


class BuildFailed(Exception):
    """A case set could not be built at all, as distinct from one case that could not."""


# --- the SVG diff -------------------------------------------------------------


def _normalise_svg(text: str) -> str:
    """`text` without the file name Visio writes into its export comment, so one drawing always hashes the same."""
    return re.sub(r"<!-- Generated by Microsoft Visio, SVG Export [^\n]*?-->", "<!-- Generated by Microsoft Visio -->", text)


def _styles(root: ElementTree.Element) -> dict[str, str]:
    """Each class the page's style sheet defines, mapped to its declarations with the spacing taken out.

    Visio numbers its classes per export (`st1`, `st2`, ...), so two exports
    can give one style two names; a shape is compared by the style a class
    stands for, never by its name.
    """
    sheet = "".join(element.text or "" for element in root.iter(f"{_SVG_NS}style"))
    return {name: _normalise_rule(body) for name, body in re.findall(r"\.([\w-]+)\s*\{([^}]*)\}", sheet)}


def _normalise_rule(body: str) -> str:
    """A rule's declarations with the spacing around them taken out and the spacing inside each value kept, as one space.

    A space inside a value is part of it: `font-family:Segoe UI` is not
    `SegoeUI`, and `stroke-dasharray:1 2` is not `12`.
    """
    declarations = []
    for declaration in body.split(";"):
        prop, colon, value = declaration.partition(":")
        if colon:
            declarations.append(f"{prop.strip()}:{' '.join(value.split())}")
    return ";".join(declarations)


def _attribute_name(name: str) -> str:
    return name.replace(_VISIO_NS, "v:").replace(_XLINK_NS, "xlink:").replace(_SVG_NS, "")


def _is_zero(value: str | None) -> bool:
    try:
        return value is not None and float(value) == 0
    except ValueError:
        return False


def _declarations(rules: Iterable[str]) -> dict[str, str]:
    """The declarations `rules` add up to, later ones winning, less any that cannot change what is drawn.

    A paint that is not drawn, `none` or fully transparent, is `none`, and
    how it would be drawn (its colour, width, caps, joins) is left out.
    Visio's export gives a text background `stroke:none` with a stroke width
    on one export and without it on the next, even for a shape nothing
    touched, and gives swimlane frames a coloured fill at `fill-opacity:0`;
    counting either would report a change that draws nothing.
    """
    declarations: dict[str, str] = {}
    for rule in rules:
        for declaration in filter(None, rule.split(";")):
            prop, _, value = declaration.partition(":")
            declarations[prop] = value
    for paint in ("fill", "stroke"):
        if declarations.get(paint) == "none" or _is_zero(declarations.get(f"{paint}-opacity")):
            declarations = {prop: value for prop, value in declarations.items() if not prop.startswith(f"{paint}-")}
            declarations[paint] = "none"
    return declarations


def _drawn_style(rules: Iterable[str]) -> str:
    """`_declarations` as one line."""
    return ";".join(f"{prop}:{value}" for prop, value in _declarations(rules).items())


_TEXT = {f"{_SVG_NS}text", f"{_SVG_NS}tspan"}
_REFERENCE = re.compile(r"url\(#([^)\s]+)\)")
_REFERENCE_DEPTH = 4
"""How many definitions deep a reference is followed: a marker uses a path, and nothing Visio writes goes deeper."""


def _rendered_text(element: ElementTree.Element) -> str:
    """The characters a `text` or `tspan` element draws, spaces and all.

    That is its own text, each run's, and the text after each of Visio's `v:`
    records inside it: Visio writes a label as `<text><v:paragraph/>
    <v:tabList/>Shape A</text>`, so the words are the tail of a record no
    renderer draws. Visio's export sets `xml:space="preserve"`, so nothing is
    stripped: a space ending one run is drawn, between two words.
    """
    pieces = [element.text or ""]
    for child in element:
        if child.tag in _TEXT:
            pieces.append(_rendered_text(child))
        pieces.append(child.tail or "")
    return "".join(pieces)


def _resolved(value: str, definitions: dict[str, str], depth: int = 0) -> str:
    """`value` with each `url(#id)` naming one of the page's definitions replaced by what that definition draws.

    Visio numbers its definitions per export (`mrkr4-16` in one, `mrkr4-55`
    in the next), so a reference is compared by what it draws, never by its
    name; and a change inside a definition, an arrowhead's size, shows on the
    shape that uses it.
    """

    def swap(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in definitions or depth >= _REFERENCE_DEPTH:
            return match.group(0)
        return "url({" + _resolved(definitions[key], definitions, depth + 1) + "})"

    return _REFERENCE.sub(swap, value)


def _describe(
    element: ElementTree.Element, styles: dict[str, str], definitions: dict[str, str], skip: Iterable[str] = ()
) -> str:
    """One drawn element as a line: its tag, its attributes with each class spelled out as its style
    and each reference as what it names, and, for text, the characters it draws.

    Visio's own `v:` attributes (a label's spelling language, what a rect is
    for) are left out: no renderer reads them. So is anything in `skip`,
    which the caller compares another way.
    """
    attributes = []
    for name, value in sorted(element.attrib.items()):
        if name == "id" or name.startswith(_VISIO_NS) or name in skip:
            continue  # Visio numbers ids per export: shape6-10 in one, shape6-12 in the next
        if name == "class":
            attributes.append("style={" + _drawn_style(styles.get(c, c) for c in value.split()) + "}")
        elif name.endswith("}href") and value.startswith("#"):
            attributes.append(f"{_attribute_name(name)}=url({value})")
        else:
            attributes.append(f"{_attribute_name(name)}={value}")
    words = [_attribute_name(element.tag), *(_resolved(a, definitions) for a in attributes)]
    if element.tag in _TEXT:
        words.append(json.dumps(_rendered_text(element)))
    return " ".join(words)


@dataclass(frozen=True)
class _Drawn:
    """What Visio drew for one shape: where it put it, and each element of it, in order."""

    transform: str
    parts: tuple[str, ...]
    group: int | None = None
    """The ID of the group it is drawn in, whose transform its own is relative to; None on the page itself."""


@dataclass(frozen=True)
class _Page:
    """What Visio drew for a page: its size, what it drew outside any shape, its shapes, and their paint order."""

    size: str
    parts: tuple[str, ...]
    shapes: dict[int, _Drawn]
    order: tuple[int, ...]
    """Shape IDs bottom first: SVG paints in document order, so a later shape covers an earlier one."""


_PAGE_SIZE = ("width", "height", "viewBox")
_NOT_DRAWN = {f"{_SVG_NS}title", f"{_SVG_NS}desc", f"{_SVG_NS}metadata"}
"""SVG elements a renderer never paints. Elements outside the SVG namespace (Visio's `v:` records of Shape Data,
user cells and text blocks) are never painted either, and are skipped with everything inside them."""
_COMPARED_ELSEWHERE = {f"{_SVG_NS}style", f"{_SVG_NS}defs"}
"""Compared through what uses them: a class as the style it stands for, a definition as what it draws."""


def _definitions(root: ElementTree.Element, styles: dict[str, str]) -> dict[str, str]:
    """Each definition in the page's `<defs>` (a marker, a path it uses), by its ID: what it and everything in it draw.

    References inside a definition are left as they are, and followed when the definition is used.
    """
    definitions = {}
    for defs in root.iter(f"{_SVG_NS}defs"):
        for element in defs.iter():
            key = element.get("id")
            if element is not defs and key:
                drawn = (e for e in element.iter() if e.tag.startswith(_SVG_NS) and e.tag not in _NOT_DRAWN)
                definitions[key] = " ".join(_describe(e, styles, {}) for e in drawn)
    return definitions


def _svg_page(text: str) -> _Page:
    """A Visio SVG export's page, shape by shape.

    A group's members are shapes of their own: a member that moves is
    reported as itself, not as a change to the group around it. The group's
    own drawing, which Visio writes in a `groupContent` element carrying the
    group's ID again, is the group's.
    """
    root = ElementTree.fromstring(_normalise_svg(text).encode("utf-8"))
    styles = _styles(root)
    definitions = _definitions(root, styles)
    page_parts: list[str] = []
    transforms: dict[int, list[str]] = {}
    parts: dict[int, list[str]] = {}
    groups: dict[int, int | None] = {}

    def walk(element: ElementTree.Element, into: list[str], hidden: bool, group: int | None) -> None:
        for child in element:
            if not child.tag.startswith(_SVG_NS) or child.tag in _NOT_DRAWN or child.tag in _COMPARED_ELSEWHERE:
                continue
            declared = _declarations(styles.get(c, c) for c in child.get("class", "").split())
            visibility = declared.get("visibility", child.get("visibility", "inherit"))
            # visibility is inherited, and a child may show itself again inside a hidden parent
            child_hidden = hidden if visibility == "inherit" else visibility in ("hidden", "collapse")
            shape_id = child.get(f"{_VISIO_NS}mID")
            if (
                child.tag == f"{_SVG_NS}g"
                and shape_id is not None
                and child.get(f"{_VISIO_NS}groupContext") != "foregroundPage"
            ):
                key = int(shape_id)
                if key not in transforms:
                    transforms[key], groups[key] = [], group
                if child.get("transform"):
                    transforms[key].append(child.get("transform", ""))
                own = parts.setdefault(key, [])
                # a style the shape's group element carries is inherited by everything it draws
                carried = _describe(child, styles, definitions, skip={"transform"})
                if carried != "g":
                    own.append(carried)
                walk(child, own, child_hidden, key)
                continue
            # an element that is not drawn is compared only as being there and not drawn
            into.append(f"{_attribute_name(child.tag)} (not drawn)" if child_hidden else _describe(child, styles, definitions))
            walk(child, into, child_hidden, group)

    # the root's own style (Visio sets the font size every label's `em` is relative to) is inherited by the whole page
    page_parts.append(_describe(root, styles, definitions, skip=_PAGE_SIZE))
    walk(root, page_parts, False, None)
    size = " ".join(f"{name}={root.get(name)}" for name in _PAGE_SIZE if root.get(name) is not None)
    shapes = {key: _Drawn(" ".join(transforms[key]), tuple(parts[key]), groups[key]) for key in transforms}
    return _Page(size, tuple(page_parts), shapes, tuple(transforms))


def _translation(transform: str) -> tuple[float, float] | None:
    match = re.match(r"\s*translate\(\s*([-\d.eE+]+)[\s,]+([-\d.eE+]+)\s*\)", transform)
    return (float(match.group(1)), float(match.group(2))) if match else None


def _moved(first: str, second: str) -> str:
    """How far a shape moved, in inches, x to the right and y up as Visio measures them; '' if that can't be read."""
    a, b = _translation(first), _translation(second)
    if a is None or b is None:
        return ""
    dx = (b[0] - a[0]) / _POINTS_PER_INCH
    dy = (a[1] - b[1]) / _POINTS_PER_INCH  # SVG's y runs down the page, Visio's up
    return f" ({dx:+.3f} in, {dy:+.3f} in)"


def _clip(part: str) -> str:
    return part if len(part) <= _CLIP else part[: _CLIP - 3] + "..."


def _changed_parts(was: tuple[str, ...], now: tuple[str, ...]) -> str:
    """Each part one drawing has and the other lacks, paired off in order."""
    gone = [p for p in was if p not in now]
    new = [p for p in now if p not in was]
    pairs = [
        f"{_clip(old) if old else '(nothing)'} -> {_clip(fresh) if fresh else '(nothing)'}"
        for old, fresh in itertools.zip_longest(gone, new, fillvalue="")
    ]
    return "; ".join(pairs or ["the same parts, reordered"])


def _diff_svgs(first: str, second: str) -> list[str]:
    """What two Visio SVG exports draw differently: the page, then each shape in ID order, then the stacking order.

    Empty if they draw the same.
    """
    first_page, second_page = _svg_page(first), _svg_page(second)
    a, b = first_page.shapes, second_page.shapes
    findings = []
    if first_page.size != second_page.size:
        findings.append(f"the page: {first_page.size} -> {second_page.size}")
    if first_page.parts != second_page.parts:
        findings.append("the page drawn differently: " + _changed_parts(first_page.parts, second_page.parts))
    for shape_id in sorted(a.keys() | b.keys()):
        if shape_id not in b:
            findings.append(f"shape {shape_id} only in the first drawing")
            continue
        if shape_id not in a:
            findings.append(f"shape {shape_id} only in the second drawing")
            continue
        was, now = a[shape_id], b[shape_id]
        if was.group != now.group:

            def where(group: int | None) -> str:
                return "on the page" if group is None else f"in shape {group}"

            findings.append(f"shape {shape_id} regrouped: {where(was.group)} -> {where(now.group)}")
        if was.transform != now.transform:
            findings.append(
                f"shape {shape_id} moved{_moved(was.transform, now.transform)}: {was.transform} -> {now.transform}"
            )
        if was.parts != now.parts:
            findings.append(f"shape {shape_id} drawn differently: " + _changed_parts(was.parts, now.parts))
    both = a.keys() & b.keys()
    first_order = [shape_id for shape_id in first_page.order if shape_id in both]
    second_order = [shape_id for shape_id in second_page.order if shape_id in both]
    if first_order != second_order:
        findings.append(
            "shapes stacked in another order, bottom first: "
            f"{', '.join(map(str, first_order))} -> {', '.join(map(str, second_order))}"
        )
    return findings


# --- building the cases ---------------------------------------------------------


@dataclass(frozen=True)
class _Case:
    """One page of one case of a built case set, as far as photographing it goes."""

    stem: str
    """What the run calls it: the case's stem, with the page when the case checks cells or glue on more than one."""
    line: str
    page: int
    """The page exported."""
    triggers: tuple[tuple[int, int, str], ...]
    """(page, shape ID, cell) for every cell the case checks, on any page; each is recalculated before the second export."""
    file: str = ""
    """The case file's stem, where it differs from `stem`."""

    @property
    def file_stem(self) -> str:
        """The stem of the `.vsdx` this case was written to."""
        return self.file or self.stem


def _read_cases(folder: Path) -> list[_Case]:
    """The cases `folder`'s `expected.json` names, in its order: one for each page a case checks cells or glue on.

    A case checking more than one page is named ``{stem}/page {n}`` for
    each. A stem names a ``.vsdx`` in one folder, so it holds no ``/``, and
    the name cannot be another case's.
    """
    expected = json.loads((folder / "expected.json").read_text(encoding="utf-8"))
    cases = []
    for stem, data in expected.items():
        triggers = tuple((int(page), int(shape), str(cell)) for page, shape, cell, _want in data["cells"])
        glued = {int(page) for page, _connector, _records in data.get("glue", [])}
        pages = sorted({page for page, _shape, _cell in triggers} | glued) or [1]
        if len(pages) == 1:
            cases.append(_Case(stem, data["line"], pages[0], triggers))
        else:
            cases += [_Case(f"{stem}/page {page}", data["line"], page, triggers, file=stem) for page in pages]
    return cases


_DRIVER = """
import importlib.util, json, sys
from pathlib import Path

builder, src, out = sys.argv[1], sys.argv[2], Path(sys.argv[3])
sys.path.insert(0, src)
import vsdxkit

spec = importlib.util.spec_from_file_location("visio_shots_cases", builder)
module = importlib.util.module_from_spec(spec)
sys.modules["visio_shots_cases"] = module
spec.loader.exec_module(module)
out.mkdir(parents=True, exist_ok=True)
cases, errors = [], {}
for build in module.CASES:
    try:
        cases.append(build(out))
    except Exception as error:
        errors[build.__name__] = f"{type(error).__name__}: {error}"
(out / "expected.json").write_text(json.dumps(module.as_json(cases), indent=2) + "\\n", encoding="utf-8")
print(json.dumps({"library": vsdxkit.__file__, "errors": errors}))
"""
"""Run in a fresh interpreter, so the library each build imports is the one asked for and no other."""


def _build(builder: Path, library_src: Path, out: Path) -> dict[str, str]:
    """Build every case `builder` defines into `out` with the library under `library_src`; each case that failed, by name.

    :raises BuildFailed: if the builder could not run, or imported a copy of
        the library other than the one under `library_src`
    """
    result = subprocess.run(
        [sys.executable, "-c", _DRIVER, str(builder), str(library_src), str(out)],
        capture_output=True,
        text=True,
        cwd=str(builder.parent),
    )
    if result.returncode != 0:
        raise BuildFailed(f"building {builder.name} with {library_src} failed:\n{result.stderr.strip()}")
    report = json.loads(result.stdout.strip().splitlines()[-1])
    library = Path(report["library"]).resolve()
    if not library.is_relative_to(library_src.resolve()):
        raise BuildFailed(f"the build imported vsdxkit from {library}, not the one asked for under {library_src}")
    return report["errors"]


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True, text=True).stdout.strip()


def _export_library(repo: Path, ref: str, dest: Path) -> tuple[Path, str]:
    """`ref`'s `src/` written under `dest` by `git archive`, leaving the checkout alone; that folder and `ref`'s commit."""
    commit = _git(repo, "rev-parse", "--verify", f"{ref}^{{commit}}")
    archive = subprocess.run(
        ["git", "-C", str(repo), "archive", "--format=tar", commit, "src"], check=True, capture_output=True
    )
    dest.mkdir(parents=True, exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(archive.stdout)) as tar:
        if hasattr(tarfile, "data_filter"):
            tar.extractall(dest, filter="data")
        else:  # Python before 3.10.12 / 3.11.4; the archive is git's own output
            tar.extractall(dest)
    return dest / "src", commit


# --- asking Visio ---------------------------------------------------------------


def _exporter_process_id(path: Path) -> int | None:
    """The ID of the Visio process `visio_export.ps1` started, from the file it writes as soon as it has one; None before that."""
    try:
        text = path.read_text(encoding="utf-8").strip()
    except FileNotFoundError:
        return None
    return int(text) if text.isdigit() else None


def _staged_names(jobs: list[tuple[str, _Case, Path]]) -> list[str]:
    """A file name for each job, unique by construction: its place in the list and its variant.

    Not derived from the case's stem: two stems a builder is free to choose,
    `foo page 1` and `foo_page_1`, would otherwise share one file.
    """
    return [f"{index:03d}_{variant}" for index, (variant, _case, _path) in enumerate(jobs)]


def _shoot(jobs: list[tuple[str, _Case, Path]], dpi: int, work: Path) -> tuple[dict, dict[str, dict[str, dict]]]:
    """Have Visio export each (variant, case, file) on open and after recalc; Visio's version, and the images by variant and stem.

    :raises visio_verify.VisioUnavailable: if Visio could not be asked
    """
    sys.path.insert(0, str(_TOOLS))
    import visio_verify

    work.mkdir(parents=True, exist_ok=True)
    keys = _staged_names(jobs)
    for key, (_variant, _case, path) in zip(keys, jobs, strict=True):
        shutil.copy2(path, work / f"{key}.vsdx")
    shots: dict[str, dict[str, dict]] = {variant: {} for variant in _VARIANTS}
    with visio_verify._staged([str(work / f"{key}.vsdx") for key in keys]) as (root, _by_name):
        staged = Path(root)

        def windows(name: str) -> str:
            return visio_verify._windows_path(str(staged / name))

        request = {
            "dpi": dpi,
            "files": [
                {
                    "path": windows(f"{key}.vsdx"),
                    "page": case.page,
                    "open": [windows(f"{key}.open.png"), windows(f"{key}.open.svg")],
                    "recalc": [windows(f"{key}.recalc.png"), windows(f"{key}.recalc.svg")],
                    "triggers": [{"page": page, "shape": shape, "cell": cell} for page, shape, cell in case.triggers],
                }
                for key, (_variant, case, _path) in zip(keys, jobs, strict=True)
            ],
        }
        request_file = staged / "request.json"
        request_file.write_text(json.dumps(request), encoding="utf-8")
        process_id_file = staged / "visio.pid"
        # -Command, the ExecutionPolicy bypass and `; exit $LASTEXITCODE`, for
        # the reasons visio_verify._observe_directory gives.
        expression = (
            f"& {visio_verify._quote(visio_verify._windows_path(str(_TOOLS / 'visio_export.ps1')))} "
            f"-Request {visio_verify._quote(visio_verify._windows_path(str(request_file)))} "
            f"-ProcessIdFile {visio_verify._quote(visio_verify._windows_path(str(process_id_file)))}; exit $LASTEXITCODE"
        )
        command = [
            visio_verify._shell(),
            "-NoProfile",
            "-NonInteractive",
            "-ExecutionPolicy",
            "Bypass",
            "-Command",
            expression,
        ]
        timeout = 60 + 30 * len(jobs)
        try:
            result = subprocess.run(command, capture_output=True, text=True, timeout=timeout)
        except subprocess.TimeoutExpired as expired:
            # only the Visio the script started, never one opened meanwhile (#463)
            process_id = _exporter_process_id(process_id_file)
            if process_id is not None:
                subprocess.run(
                    [
                        visio_verify._shell(),
                        "-NoProfile",
                        "-NonInteractive",
                        "-Command",
                        f"Stop-Process -Id {process_id} -Force",
                    ],
                    capture_output=True,
                    text=True,
                    timeout=60,
                )
            raise visio_verify.VisioUnavailable(
                f"visio_export.ps1 did not answer within {timeout}s and was killed"
                + (
                    f"; so was the Visio it started, process {process_id}"
                    if process_id is not None
                    else "; it had not started Visio"
                )
            ) from expired
        if result.returncode != 0 or not result.stdout.strip():
            raise visio_verify.VisioUnavailable(
                f"visio_export.ps1 exited {result.returncode}: {result.stderr.strip() or '(no output)'}"
            )
        payload = json.loads(result.stdout.strip())
        if len(payload["files"]) != len(jobs):
            raise visio_verify.VisioUnavailable(
                f"asked about {len(jobs)} files; visio_export.ps1 answered {len(payload['files'])}"
            )
        for key, (variant, case, _path), record in zip(keys, jobs, payload["files"], strict=True):
            if "error" in record:
                shots[variant][case.stem] = {"error": record["error"]}
                continue
            shots[variant][case.stem] = {
                state: {
                    "svg": (staged / f"{key}.{state}.svg").read_text(encoding="utf-8"),
                    "png": (staged / f"{key}.{state}.png").read_bytes(),
                }
                for state in _STATES
            } | {"triggered": int(record["triggered"]), "asked": len(case.triggers)}
    return payload["visio"], shots


# --- the store --------------------------------------------------------------------


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _put(folder: Path, data: bytes, suffix: str) -> str:
    """Store `data` once under `folder`, named by its hash; the hash."""
    digest = _sha256(data)
    target = folder / digest[:2] / f"{digest}{suffix}"
    if not target.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
    return digest


def _svg_object(store: Path, digest: str) -> str:
    return (store / "objects" / digest[:2] / f"{digest}.svg").read_text(encoding="utf-8")


def _findings(shots: dict[str, dict[str, dict]], stem: str) -> dict[str, list[str] | None]:
    """Every comparison the run makes for one case; None where one side has no drawing."""

    def svg(variant: str, state: str) -> str | None:
        shot = shots.get(variant, {}).get(stem)
        return None if shot is None or "error" in shot else shot[state]["svg"]

    def diff(first: str | None, second: str | None) -> list[str] | None:
        return None if first is None or second is None else _diff_svgs(first, second)

    return {
        _STALE: diff(svg("candidate", "open"), svg("candidate", "recalc")),
        _REF_STATES: diff(svg("ref", "open"), svg("ref", "recalc")),
        _REF_TO_CANDIDATE: diff(svg("ref", "recalc"), svg("candidate", "recalc")),
        _BEFORE_TO_CANDIDATE: diff(svg("before", "recalc"), svg("candidate", "recalc")),
    }


def _verdict(found: list[str] | None) -> str:
    if found is None:
        return "-"
    return "same" if not found else f"{len(found)} difference{'s' if len(found) != 1 else ''}"


def _failures(manifest: dict) -> list[str]:
    """Why the run fails: a candidate case stale on open, or one that was never judged; empty if it passes.

    A case the candidate could not build, or Visio could not export, never
    reached a verdict, and a run that skipped it has not shown anything.
    """
    failures = [
        f"the candidate could not build {name}: {error}"
        for name, error in manifest["build_errors"].get("candidate", {}).items()
    ]
    for stem, case in manifest["cases"].items():
        shot = case["shots"].get("candidate")
        if shot is None:
            failures.append(f"{stem} was not judged: Visio was not asked to export it")
        elif "error" in shot:
            failures.append(f"{stem} was not judged: Visio could not export it: {shot['error']}")
        elif shot.get("triggered", 0) < shot.get("asked", 0):
            # a shape or cell Visio no longer has recalculates nothing, so
            # its two exports agree whether or not it was stale
            failures.append(
                f"{stem} was not judged: Visio recalculated {shot['triggered']} of the {shot['asked']} cells it checks"
            )
        elif case["stale_on_open"]:
            failures.append(f"{stem} is stale on open")
    return failures


def _summary(manifest: dict) -> str:
    """The run as Markdown, for a person reading the store or a pull request."""
    against = manifest["against"]
    ref = f"`{against['ref']}` ({against['commit'][:7]})" if against else "no ref"
    builder = manifest.get("builder")
    built = f"cases from `{builder['path']}` ({builder['sha256'][:7]}); " if builder else ""
    lines = [
        f"# Visio shots {manifest['run']}",
        "",
        f"Candidate {manifest['commit'][:7]} on `{manifest['branch']}`{' with uncommitted changes' if manifest['dirty'] else ''}; "
        f"{built}against {ref}; Visio {manifest['visio'].get('version', '?')} build {manifest['visio'].get('build', '?')}; "
        f"{manifest['dpi']} dpi.",
        "",
        "| Case | Candidate on open vs after recalc | Ref vs candidate | Before vs candidate |",
        "|---|---|---|---|",
    ]
    for stem, case in manifest["cases"].items():
        found = case["findings"]
        stale = "**STALE ON OPEN**, " + _verdict(found[_STALE]) if case["stale_on_open"] else _verdict(found[_STALE])
        lines.append(f"| {stem} | {stale} | {_verdict(found[_REF_TO_CANDIDATE])} | {_verdict(found[_BEFORE_TO_CANDIDATE])} |")
    for side, errors in manifest["build_errors"].items():
        for name, error in errors.items():
            lines.append(f"\n{side} could not build `{name}`: {error}")
    failures = _failures(manifest)
    lines += ["", f"**FAIL**: {len(failures)} reason(s)" if failures else "**PASS**", *[f"- {reason}" for reason in failures]]
    for stem, case in manifest["cases"].items():
        lines += ["", f"## {stem}", "", case["line"]]
        for heading, found in case["findings"].items():
            if found:
                lines += ["", f"{heading}:", *[f"- {finding}" for finding in found]]
    return "\n".join(lines) + "\n"


def _report(manifest: dict, images: dict[str, dict[str, dict[str, bytes]]]) -> str:
    """The run as one HTML page with every image inside it, for a person to open anywhere."""
    style = (
        "body{font-family:sans-serif;margin:16px;background:#fff;color:#111}table{border-collapse:collapse}"
        "td{vertical-align:top;padding:4px;border:1px solid #ccc}img{max-width:560px;height:auto}"
        ".stale{color:#b00020;font-weight:bold}li{font-family:monospace;font-size:12px}"
    )
    parts = [
        f"<!doctype html><meta charset='utf-8'><title>Visio shots {html.escape(manifest['run'])}</title><style>{style}</style>"
    ]
    parts.append(
        f"<h1>Visio shots {html.escape(manifest['run'])}</h1><pre>{html.escape(_summary(manifest).split(chr(10) + '## ')[0])}</pre>"
    )
    for stem, case in manifest["cases"].items():
        flag = " <span class='stale'>stale on open</span>" if case["stale_on_open"] else ""
        parts.append(f"<h2>{html.escape(stem)}{flag}</h2><p>{html.escape(case['line'])}</p><table><tr><td></td>")
        parts += [f"<td>{variant}</td>" for variant in _VARIANTS]
        parts.append("</tr>")
        for state in _STATES:
            parts.append(f"<tr><td>{_STATE_WORDS[state]}</td>")
            for variant in _VARIANTS:
                png = images.get(variant, {}).get(stem, {}).get(state)
                cell = f"<img src='data:image/png;base64,{base64.b64encode(png).decode('ascii')}'>" if png else "-"
                parts.append(f"<td>{cell}</td>")
            parts.append("</tr>")
        parts.append("</table>")
        for heading, found in case["findings"].items():
            if found:
                parts.append(
                    f"<p>{html.escape(heading)}</p><ul>" + "".join(f"<li>{html.escape(f)}</li>" for f in found) + "</ul>"
                )
    return "".join(parts)


def _new_run_dir(store: Path, run_id: str) -> Path:
    """A folder for one run's record that no other run has: `run_id`, or `run_id-2`, `-3`, ... if it is taken.

    Created exclusively, so two runs of one commit started in the same
    second never write into one record.
    """
    (store / "runs").mkdir(parents=True, exist_ok=True)
    for attempt in itertools.count(1):
        run_dir = store / "runs" / (run_id if attempt == 1 else f"{run_id}-{attempt}")
        try:
            run_dir.mkdir()
        except FileExistsError:
            continue
        return run_dir
    raise AssertionError("unreachable: itertools.count never ends")


def _record_run(
    store: Path,
    identity: dict,
    lines: dict[str, str],
    shots: dict[str, dict[str, dict]],
    *,
    build_errors: dict[str, dict[str, str]],
) -> dict:
    """Write one run into `store`: its manifest, summary and SVGs (committed), its PNGs and report (local); the manifest."""
    cases: dict[str, dict] = {}
    images: dict[str, dict[str, dict[str, bytes]]] = {}
    for stem, line in lines.items():
        stored: dict[str, dict] = {}
        for variant in _VARIANTS:
            shot = shots.get(variant, {}).get(stem)
            if shot is None:
                continue
            if "error" in shot:
                stored[variant] = {"error": shot["error"]}
                continue
            stored[variant] = {
                state: {
                    "svg": _put(store / "objects", _normalise_svg(shot[state]["svg"]).encode("utf-8"), ".svg"),
                    "png": _put(store / "local" / "png", shot[state]["png"], ".png"),
                }
                for state in _STATES
            } | {counted: shot[counted] for counted in ("triggered", "asked") if counted in shot}
            images.setdefault(variant, {})[stem] = {state: shot[state]["png"] for state in _STATES}
        found = _findings(shots, stem)
        cases[stem] = {"line": line, "shots": stored, "findings": found, "stale_on_open": bool(found[_STALE])}
    run_dir = _new_run_dir(store, identity["run"])
    identity = identity | {"run": run_dir.name}
    manifest = {**identity, "build_errors": build_errors, "cases": cases}

    (run_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (run_dir / "summary.md").write_text(_summary(manifest), encoding="utf-8")
    local = store / "local" / identity["run"]
    local.mkdir(parents=True, exist_ok=True)
    (local / "report.html").write_text(_report(manifest, images), encoding="utf-8")
    entry = {key: identity[key] for key in ("run", "created", "commit", "branch", "dirty", "against")} | {
        "cases": len(cases),
        "stale_on_open": [stem for stem, case in cases.items() if case["stale_on_open"]],
        "failures": _failures(manifest),
    }
    with (store / "index.jsonl").open("a", encoding="utf-8") as index:
        index.write(json.dumps(entry) + "\n")
    return manifest


def _manifest(store: Path, run: str) -> dict:
    return json.loads((store / "runs" / run / "manifest.json").read_text(encoding="utf-8"))


def _diff_runs(store: Path, first: str, second: str) -> list[str]:
    """What differs between two recorded runs: each reason one fails for and the other doesn't, then each case whose
    candidate verdict or drawing differs, with what changed.

    A case stale in one run is reported with its case, below, not among the reasons.
    """
    first_manifest, second_manifest = _manifest(store, first), _manifest(store, second)
    first_failures = [f for f in _failures(first_manifest) if not f.endswith(" is stale on open")]
    second_failures = [f for f in _failures(second_manifest) if not f.endswith(" is stale on open")]
    lines = [f"fails only in {first}: {reason}" for reason in first_failures if reason not in second_failures]
    lines += [f"fails only in {second}: {reason}" for reason in second_failures if reason not in first_failures]
    a, b = first_manifest["cases"], second_manifest["cases"]
    for stem in sorted(a.keys() | b.keys()):
        if stem not in b or stem not in a:
            lines.append(f"{stem}: only in {first if stem in a else second}")
            continue
        was, now = a[stem], b[stem]
        header = []
        if was["stale_on_open"] != now["stale_on_open"]:
            stale, fresh = (first, second) if was["stale_on_open"] else (second, first)
            header.append(f"{stem}: stale on open in {stale}, not in {fresh}")
        details = []
        old_shots, new_shots = was["shots"].get("candidate", {}), now["shots"].get("candidate", {})
        for state in _STATES:
            old, new = old_shots.get(state), new_shots.get(state)
            if old is None or new is None:
                if old != new:
                    details.append(f"  {_STATE_WORDS[state]}: drawn in only one run")
                continue
            if old["svg"] != new["svg"]:
                changes = _diff_svgs(_svg_object(store, old["svg"]), _svg_object(store, new["svg"]))
                details += [f"  {_STATE_WORDS[state]}: {change}" for change in changes]
        if details and not header:
            header.append(f"{stem}: the candidate is drawn differently")
        lines += header + details
    return lines


# --- commands -----------------------------------------------------------------------


def _builder_identity(builder: Path) -> dict[str, str]:
    """The case module a run built from: where it is, and its content's hash.

    The hash is what names it. A builder outside this repository is not
    covered by the commit or the dirty check, and two edits of one file are
    two builders.
    """
    path = builder.resolve()
    shown = str(path.relative_to(_REPO)) if path.is_relative_to(_REPO) else str(builder)
    return {"path": shown, "sha256": _sha256(path.read_bytes())}


def _source_identity(builder: Path) -> dict:
    """The code a run builds from: taken before the build, since the tree can change during a long export."""
    return {
        "commit": _git(_REPO, "rev-parse", "HEAD"),
        "branch": _git(_REPO, "branch", "--show-current") or "(detached)",
        "dirty": bool(_git(_REPO, "status", "--porcelain", "--", "src", "tools", "tests")),
        "builder": _builder_identity(builder),
    }


def _jobs(
    candidate_dir: Path, cases: list[_Case], ref_dir: Path, ref_cases: dict[str, _Case]
) -> list[tuple[str, _Case, Path]]:
    """Every (variant, case, file) to photograph: each case's `.before` file where it has one, the ref's build, the candidate's.

    The `.before` file is photographed with the candidate's case, whose
    triggers name shapes the fixture already has (a trigger naming a shape
    the case created is skipped by the export). The ref's build is
    photographed with the case the ref's own build wrote: its library may
    have given a shape the case created another ID.
    """
    jobs = []
    for case in cases:
        before = candidate_dir / f"{case.file_stem}.before.vsdx"
        if before.exists():
            jobs.append(("before", case, before))
        if case.stem in ref_cases:
            jobs.append(("ref", ref_cases[case.stem], ref_dir / f"{case.file_stem}.vsdx"))
        jobs.append(("candidate", case, candidate_dir / f"{case.file_stem}.vsdx"))
    return jobs


def _command_run(builder: Path, against: str | None, store: Path, dpi: int) -> int:
    sys.path.insert(0, str(_TOOLS))
    import visio_verify

    now = datetime.datetime.now(datetime.timezone.utc)
    source = _source_identity(builder)
    with tempfile.TemporaryDirectory(prefix="visio-shots-") as scratch:
        work = Path(scratch)
        candidate = work / "candidate"
        errors = {"candidate": _build(builder, _REPO / "src", candidate)}
        ref_info, ref_cases = None, {}
        if against:
            ref_src, commit = _export_library(_REPO, against, work / "ref-library")
            errors["ref"] = _build(builder, ref_src, work / "ref")
            ref_info = {"ref": against, "commit": commit}
            ref_cases = {case.stem: case for case in _read_cases(work / "ref")}
        cases = _read_cases(candidate)
        if not cases:
            print(f"{builder.name} built no cases: {errors['candidate']}", file=sys.stderr)
            return 2
        try:
            visio, shots = _shoot(_jobs(candidate, cases, work / "ref", ref_cases), dpi, work / "shots")
        except visio_verify.VisioUnavailable as error:
            print(f"Visio is not usable from here: {error}", file=sys.stderr)
            return 2
    run_id = f"{now:%Y%m%dT%H%M%SZ}_{source['commit'][:7]}"
    identity = {"run": run_id, "created": now.isoformat(timespec="seconds"), **source}
    identity |= {"against": ref_info, "visio": visio, "dpi": dpi}
    manifest = _record_run(store, identity, {case.stem: case.line for case in cases}, shots, build_errors=errors)
    print(_summary(manifest).split("\n## ")[0])
    recorded = manifest["run"]
    print(f"recorded {store / 'runs' / recorded}; images in {store / 'local' / recorded / 'report.html'}")
    return 1 if _failures(manifest) else 0


def main(argv: list[str] | None = None) -> int:
    """Run the harness; 0 when every candidate case was judged and none is stale on open, 1 otherwise, 2 when it could not run."""
    parser = argparse.ArgumentParser(prog="visio_shots.py", description=__doc__.split("\n\n")[0])
    commands = parser.add_subparsers(dest="command", required=True)
    run = commands.add_parser("run", help="build, photograph and record the case set")
    run.add_argument("--against", help="a git ref whose library builds the comparison column, e.g. main")
    run.add_argument("--builder", type=Path, default=_BUILDER, help="the case module (default: tools/writes_land_cases.py)")
    run.add_argument("--store", type=Path, default=_STORE, help="where runs are recorded (default: .hermes/visio-shots)")
    run.add_argument("--dpi", type=int, default=150, help="PNG resolution (default: 150)")
    diff = commands.add_parser("diff-runs", help="what changed between two recorded runs")
    diff.add_argument("first")
    diff.add_argument("second")
    diff.add_argument("--store", type=Path, default=_STORE)
    args = parser.parse_args(argv)

    if args.command == "diff-runs":
        lines = _diff_runs(args.store, args.first, args.second)
        print("\n".join(lines) if lines else f"no case is drawn differently between {args.first} and {args.second}")
        return 0
    try:
        return _command_run(args.builder.resolve(), args.against, args.store, args.dpi)
    except BuildFailed as error:
        print(error, file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
