"""Photograph what Visio draws for a case set, compare it, and keep a record of every run.

Usage:
    python tools/visio_shots.py run [--against REF] [--builder PATH] [--store DIR] [--dpi N]
    python tools/visio_shots.py diff-runs <run-a> <run-b> [--store DIR]

``run`` builds the case set twice when ``--against`` names a git ref: once
with this working tree's library (the candidate) and once with that ref's,
exported with ``git archive`` (the ref). The builder is
``tools/writes_land_cases.py`` unless ``--builder`` names another module that
keeps its contract: ``CASES``, callables that each write one case into a
folder and return it, and ``as_json``, which turns them into
``expected.json``. A case the ref's library cannot build is recorded, and
the rest still run.

A Windows Visio (``tools/visio_export.ps1``) exports each case's page as PNG
and SVG as it opens, then again after ``Cell.Trigger()`` recalculates every
cell the case checks. It does this for the candidate, the ref and the
untouched fixture (``<case>.before.vsdx``). The SVG names each shape by its
Visio ID and carries its position, path, text and style, so two exports are
compared shape by shape, exactly. No pixels are compared and no text is
recognised.

Visio draws from the values a file caches, so a candidate drawn differently
after recalculating was stale on open: the file said one thing and would
show another as soon as anything recalculated (#461). ``run`` exits 1 when
any case is. Differences from the ref or from the fixture are what the
change did, and are reported, not judged.

Every run is recorded in the store (``.hermes/visio-shots`` by default):
``runs/<run>/manifest.json`` and ``summary.md``, each SVG once under
``objects/`` by its hash, and one line in ``index.jsonl``. All of that is
text and is committed. The PNGs and a self-contained ``report.html`` go under
``local/``, which git ignores. ``diff-runs`` lists the cases whose candidate
drawing or verdict changed between two recorded runs.
"""

from __future__ import annotations

import argparse
import base64
import datetime
import hashlib
import html
import io
import itertools
import json
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from xml.etree import ElementTree

_REPO = Path(__file__).resolve().parent.parent
_TOOLS = _REPO / "tools"
_STORE = _REPO / ".hermes" / "visio-shots"
_BUILDER = _TOOLS / "writes_land_cases.py"

_VARIANTS = ("before", "ref", "candidate")
"""The columns of every comparison: the untouched fixture, the ref's build, this tree's build."""
_STATES = ("open", "recalc")
"""When each export is taken: as the file opens, and after the checked cells recalculate."""
_STATE_WORDS = {"open": "on open", "recalc": "after recalc"}

_SVG_NS = "{http://www.w3.org/2000/svg}"
_VISIO_NS = "{http://schemas.microsoft.com/visio/2003/SVGExtensions/}"
_POINTS_PER_INCH = 72.0
_CLIP = 240
"""The longest a drawn part is quoted in a finding; a path's `d` can run to kilobytes."""

_STALE = "candidate on open -> after recalc"
_REF_STATES = "ref on open -> after recalc"
_REF_TO_CANDIDATE = "ref -> candidate, after recalc"
_BEFORE_TO_CANDIDATE = "before -> candidate, after recalc"


class BuildFailed(Exception):
    """A case set could not be built at all, as distinct from one case that could not."""


# --- the SVG diff -------------------------------------------------------------


def _normalise_svg(text: str) -> str:
    """`text` without the file name Visio writes into its export comment, so one drawing always hashes the same."""
    return re.sub(r"<!-- Generated by Microsoft Visio, SVG Export [^\n]*?-->", "<!-- Generated by Microsoft Visio -->", text)


def _styles(root: ElementTree.Element) -> dict[str, str]:
    """Each class the page's style sheet defines, mapped to its declarations with the spacing taken out.

    Visio numbers its classes per export (`st1`, `st2`, ...), so two exports
    can give one style two names; a shape is compared by the style a class
    stands for, never by its name.
    """
    sheet = "".join(element.text or "" for element in root.iter(f"{_SVG_NS}style"))
    return {name: re.sub(r"\s+", "", body) for name, body in re.findall(r"\.([\w-]+)\s*\{([^}]*)\}", sheet)}


def _attribute_name(name: str) -> str:
    return name.replace(_VISIO_NS, "v:").replace(_SVG_NS, "")


def _drawn_style(rules: Iterable[str]) -> str:
    """The declarations `rules` add up to, later ones winning, less any that cannot change what is drawn.

    With `stroke:none` no stroke is drawn, so how one would be drawn (its
    width, caps, joins) is left out. Visio's export gives a text background
    `stroke:none` with a stroke width on one export and without it on the
    next, even for a shape nothing touched; counting it would report a
    change that draws nothing.
    """
    declarations: dict[str, str] = {}
    for rule in rules:
        for declaration in filter(None, rule.split(";")):
            prop, _, value = declaration.partition(":")
            declarations[prop] = value
    if declarations.get("stroke") == "none":
        declarations = {prop: value for prop, value in declarations.items() if not prop.startswith("stroke-")}
    return ";".join(f"{prop}:{value}" for prop, value in declarations.items())


def _describe(element: ElementTree.Element, styles: dict[str, str]) -> str:
    """One drawn element as a line: its tag, its attributes with each class spelled out as its style, and its text."""
    tag = _attribute_name(element.tag)
    attributes = []
    for name, value in sorted(element.attrib.items()):
        if name == "id":
            continue  # Visio numbers these per export: shape6-10 in one, shape6-12 in the next
        if name == "class":
            attributes.append("style={" + _drawn_style(styles.get(c, c) for c in value.split()) + "}")
        else:
            attributes.append(f"{_attribute_name(name)}={value}")
    text = (element.text or "").strip()
    tail = (element.tail or "").strip()
    return " ".join([tag, *attributes, *([json.dumps(text)] if text else []), *([f"+{json.dumps(tail)}"] if tail else [])])


@dataclass(frozen=True)
class _Drawn:
    """What Visio drew for one shape: where it put it, and each element of it, in order."""

    transform: str
    parts: tuple[str, ...]


def _svg_shapes(text: str) -> dict[int, _Drawn]:
    """Every shape in a Visio SVG export, by its Visio ID.

    A group's members are shapes of their own: a member that moves is
    reported as itself, not as a change to the group around it.
    """
    root = ElementTree.fromstring(_normalise_svg(text).encode("utf-8"))
    styles = _styles(root)
    shapes: dict[int, _Drawn] = {}

    def walk(element: ElementTree.Element, parts: list[str] | None) -> None:
        for child in element:
            shape_id = child.get(f"{_VISIO_NS}mID")
            if (
                child.tag == f"{_SVG_NS}g"
                and shape_id is not None
                and child.get(f"{_VISIO_NS}groupContext") != "foregroundPage"
            ):
                own: list[str] = []
                walk(child, own)
                shapes[int(shape_id)] = _Drawn(child.get("transform", ""), tuple(own))
                continue
            if parts is not None and child.tag != f"{_SVG_NS}title":
                parts.append(_describe(child, styles))
            walk(child, parts)

    walk(root, None)
    return shapes


def _translation(transform: str) -> tuple[float, float] | None:
    match = re.match(r"\s*translate\(\s*([-\d.eE+]+)[\s,]+([-\d.eE+]+)\s*\)", transform)
    return (float(match.group(1)), float(match.group(2))) if match else None


def _moved(first: str, second: str) -> str:
    """How far a shape moved, in inches, x to the right and y up as Visio measures them; '' if that can't be read."""
    a, b = _translation(first), _translation(second)
    if a is None or b is None:
        return ""
    dx = (b[0] - a[0]) / _POINTS_PER_INCH
    dy = (a[1] - b[1]) / _POINTS_PER_INCH  # SVG's y runs down the page, Visio's up
    return f" ({dx:+.3f} in, {dy:+.3f} in)"


def _clip(part: str) -> str:
    return part if len(part) <= _CLIP else part[: _CLIP - 3] + "..."


def _diff_svgs(first: str, second: str) -> list[str]:
    """Each shape two Visio SVG exports draw differently, in shape ID order; empty if they draw the same."""
    a, b = _svg_shapes(first), _svg_shapes(second)
    findings = []
    for shape_id in sorted(a.keys() | b.keys()):
        if shape_id not in b:
            findings.append(f"shape {shape_id} only in the first drawing")
            continue
        if shape_id not in a:
            findings.append(f"shape {shape_id} only in the second drawing")
            continue
        was, now = a[shape_id], b[shape_id]
        if was.transform != now.transform:
            findings.append(
                f"shape {shape_id} moved{_moved(was.transform, now.transform)}: {was.transform} -> {now.transform}"
            )
        if was.parts != now.parts:
            gone = [p for p in was.parts if p not in now.parts]
            new = [p for p in now.parts if p not in was.parts]
            pairs = [
                f"{_clip(old) if old else '(nothing)'} -> {_clip(fresh) if fresh else '(nothing)'}"
                for old, fresh in itertools.zip_longest(gone, new, fillvalue="")
            ]
            findings.append(f"shape {shape_id} drawn differently: " + "; ".join(pairs or ["the same parts, reordered"]))
    return findings


# --- building the cases ---------------------------------------------------------


@dataclass(frozen=True)
class _Case:
    """One case of a built case set, as far as photographing it goes."""

    stem: str
    line: str
    page: int
    """The page exported: the first one the case checks a cell on."""
    triggers: tuple[tuple[int, int, str], ...]
    """(page, shape ID, cell) for every cell the case checks; each is recalculated before the second export."""


def _read_cases(folder: Path) -> list[_Case]:
    """The cases `folder`'s `expected.json` names, in its order."""
    expected = json.loads((folder / "expected.json").read_text(encoding="utf-8"))
    cases = []
    for stem, data in expected.items():
        triggers = tuple((int(page), int(shape), str(cell)) for page, shape, cell, _want in data["cells"])
        cases.append(_Case(stem, data["line"], min((t[0] for t in triggers), default=1), triggers))
    return cases


_DRIVER = """
import importlib.util, json, sys
from pathlib import Path

builder, src, out = sys.argv[1], sys.argv[2], Path(sys.argv[3])
sys.path.insert(0, src)
import vsdxkit

spec = importlib.util.spec_from_file_location("visio_shots_cases", builder)
module = importlib.util.module_from_spec(spec)
sys.modules["visio_shots_cases"] = module
spec.loader.exec_module(module)
out.mkdir(parents=True, exist_ok=True)
cases, errors = [], {}
for build in module.CASES:
    try:
        cases.append(build(out))
    except Exception as error:
        errors[build.__name__] = f"{type(error).__name__}: {error}"
(out / "expected.json").write_text(json.dumps(module.as_json(cases), indent=2) + "\\n", encoding="utf-8")
print(json.dumps({"library": vsdxkit.__file__, "errors": errors}))
"""
"""Run in a fresh interpreter, so the library each build imports is the one asked for and no other."""


def _build(builder: Path, library_src: Path, out: Path) -> dict[str, str]:
    """Build every case `builder` defines into `out` with the library under `library_src`; each case that failed, by name.

    :raises BuildFailed: if the builder could not run, or imported a copy of
        the library other than the one under `library_src`
    """
    result = subprocess.run(
        [sys.executable, "-c", _DRIVER, str(builder), str(library_src), str(out)],
        capture_output=True,
        text=True,
        cwd=str(builder.parent),
    )
    if result.returncode != 0:
        raise BuildFailed(f"building {builder.name} with {library_src} failed:\n{result.stderr.strip()}")
    report = json.loads(result.stdout.strip().splitlines()[-1])
    library = Path(report["library"]).resolve()
    if not library.is_relative_to(library_src.resolve()):
        raise BuildFailed(f"the build imported vsdxkit from {library}, not the one asked for under {library_src}")
    return report["errors"]


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True, text=True).stdout.strip()


def _export_library(repo: Path, ref: str, dest: Path) -> tuple[Path, str]:
    """`ref`'s `src/` written under `dest` by `git archive`, leaving the checkout alone; that folder and `ref`'s commit."""
    commit = _git(repo, "rev-parse", "--verify", f"{ref}^{{commit}}")
    archive = subprocess.run(
        ["git", "-C", str(repo), "archive", "--format=tar", commit, "src"], check=True, capture_output=True
    )
    dest.mkdir(parents=True, exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(archive.stdout)) as tar:
        if hasattr(tarfile, "data_filter"):
            tar.extractall(dest, filter="data")
        else:  # Python before 3.10.12 / 3.11.4; the archive is git's own output
            tar.extractall(dest)
    return dest / "src", commit


# --- asking Visio ---------------------------------------------------------------


def _shoot(jobs: list[tuple[str, _Case, Path]], dpi: int, work: Path) -> tuple[dict, dict[str, dict[str, dict]]]:
    """Have Visio export each (variant, case, file) on open and after recalc; Visio's version, and the images by variant and stem.

    :raises visio_verify.VisioUnavailable: if Visio could not be asked
    """
    sys.path.insert(0, str(_TOOLS))
    import visio_verify

    work.mkdir(parents=True, exist_ok=True)
    keys = []
    for variant, case, path in jobs:
        key = f"{variant}__{case.stem}"
        shutil.copy2(path, work / f"{key}.vsdx")
        keys.append(key)
    shots: dict[str, dict[str, dict]] = {variant: {} for variant in _VARIANTS}
    with visio_verify._staged([str(work / f"{key}.vsdx") for key in keys]) as (root, _by_name):
        staged = Path(root)

        def windows(name: str) -> str:
            return visio_verify._windows_path(str(staged / name))

        request = {
            "dpi": dpi,
            "files": [
                {
                    "path": windows(f"{key}.vsdx"),
                    "page": case.page,
                    "open": [windows(f"{key}.open.png"), windows(f"{key}.open.svg")],
                    "recalc": [windows(f"{key}.recalc.png"), windows(f"{key}.recalc.svg")],
                    "triggers": [{"page": page, "shape": shape, "cell": cell} for page, shape, cell in case.triggers],
                }
                for key, (_variant, case, _path) in zip(keys, jobs, strict=True)
            ],
        }
        request_file = staged / "request.json"
        request_file.write_text(json.dumps(request), encoding="utf-8")
        # -Command, the ExecutionPolicy bypass and `; exit $LASTEXITCODE`, for
        # the reasons visio_verify._observe_directory gives.
        expression = (
            f"& {visio_verify._quote(visio_verify._windows_path(str(_TOOLS / 'visio_export.ps1')))} "
            f"-Request {visio_verify._quote(visio_verify._windows_path(str(request_file)))}; exit $LASTEXITCODE"
        )
        command = [
            visio_verify._shell(),
            "-NoProfile",
            "-NonInteractive",
            "-ExecutionPolicy",
            "Bypass",
            "-Command",
            expression,
        ]
        before = visio_verify._visio_pids()
        timeout = 60 + 30 * len(jobs)
        try:
            result = subprocess.run(command, capture_output=True, text=True, timeout=timeout)
        except subprocess.TimeoutExpired as expired:
            killed = visio_verify._reap_visio(before)
            raise visio_verify.VisioUnavailable(
                f"visio_export.ps1 did not answer within {timeout}s and was killed"
                + (f" (stranded process {', '.join(map(str, killed))} also killed)" if killed else "")
            ) from expired
        if result.returncode != 0 or not result.stdout.strip():
            raise visio_verify.VisioUnavailable(
                f"visio_export.ps1 exited {result.returncode}: {result.stderr.strip() or '(no output)'}"
            )
        payload = json.loads(result.stdout.strip())
        if len(payload["files"]) != len(jobs):
            raise visio_verify.VisioUnavailable(
                f"asked about {len(jobs)} files; visio_export.ps1 answered {len(payload['files'])}"
            )
        for key, (variant, case, _path), record in zip(keys, jobs, payload["files"], strict=True):
            if "error" in record:
                shots[variant][case.stem] = {"error": record["error"]}
                continue
            shots[variant][case.stem] = {
                state: {
                    "svg": (staged / f"{key}.{state}.svg").read_text(encoding="utf-8"),
                    "png": (staged / f"{key}.{state}.png").read_bytes(),
                }
                for state in _STATES
            }
    return payload["visio"], shots


# --- the store --------------------------------------------------------------------


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _put(folder: Path, data: bytes, suffix: str) -> str:
    """Store `data` once under `folder`, named by its hash; the hash."""
    digest = _sha256(data)
    target = folder / digest[:2] / f"{digest}{suffix}"
    if not target.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
    return digest


def _svg_object(store: Path, digest: str) -> str:
    return (store / "objects" / digest[:2] / f"{digest}.svg").read_text(encoding="utf-8")


def _findings(shots: dict[str, dict[str, dict]], stem: str) -> dict[str, list[str] | None]:
    """Every comparison the run makes for one case; None where one side has no drawing."""

    def svg(variant: str, state: str) -> str | None:
        shot = shots.get(variant, {}).get(stem)
        return None if shot is None or "error" in shot else shot[state]["svg"]

    def diff(first: str | None, second: str | None) -> list[str] | None:
        return None if first is None or second is None else _diff_svgs(first, second)

    return {
        _STALE: diff(svg("candidate", "open"), svg("candidate", "recalc")),
        _REF_STATES: diff(svg("ref", "open"), svg("ref", "recalc")),
        _REF_TO_CANDIDATE: diff(svg("ref", "recalc"), svg("candidate", "recalc")),
        _BEFORE_TO_CANDIDATE: diff(svg("before", "recalc"), svg("candidate", "recalc")),
    }


def _verdict(found: list[str] | None) -> str:
    if found is None:
        return "-"
    return "same" if not found else f"{len(found)} difference{'s' if len(found) != 1 else ''}"


def _summary(manifest: dict) -> str:
    """The run as Markdown, for a person reading the store or a pull request."""
    against = manifest["against"]
    ref = f"`{against['ref']}` ({against['commit'][:7]})" if against else "no ref"
    lines = [
        f"# Visio shots {manifest['run']}",
        "",
        f"Candidate {manifest['commit'][:7]} on `{manifest['branch']}`{' with uncommitted changes' if manifest['dirty'] else ''}; "
        f"against {ref}; Visio {manifest['visio'].get('version', '?')} build {manifest['visio'].get('build', '?')}; "
        f"{manifest['dpi']} dpi.",
        "",
        "| Case | Candidate on open vs after recalc | Ref vs candidate | Before vs candidate |",
        "|---|---|---|---|",
    ]
    for stem, case in manifest["cases"].items():
        found = case["findings"]
        stale = "**STALE ON OPEN**, " + _verdict(found[_STALE]) if case["stale_on_open"] else _verdict(found[_STALE])
        lines.append(f"| {stem} | {stale} | {_verdict(found[_REF_TO_CANDIDATE])} | {_verdict(found[_BEFORE_TO_CANDIDATE])} |")
    for side, errors in manifest["build_errors"].items():
        for name, error in errors.items():
            lines.append(f"\n{side} could not build `{name}`: {error}")
    for stem, case in manifest["cases"].items():
        lines += ["", f"## {stem}", "", case["line"]]
        for heading, found in case["findings"].items():
            if found:
                lines += ["", f"{heading}:", *[f"- {finding}" for finding in found]]
    return "\n".join(lines) + "\n"


def _report(manifest: dict, images: dict[str, dict[str, dict[str, bytes]]]) -> str:
    """The run as one HTML page with every image inside it, for a person to open anywhere."""
    style = (
        "body{font-family:sans-serif;margin:16px;background:#fff;color:#111}table{border-collapse:collapse}"
        "td{vertical-align:top;padding:4px;border:1px solid #ccc}img{max-width:560px;height:auto}"
        ".stale{color:#b00020;font-weight:bold}li{font-family:monospace;font-size:12px}"
    )
    parts = [
        f"<!doctype html><meta charset='utf-8'><title>Visio shots {html.escape(manifest['run'])}</title><style>{style}</style>"
    ]
    parts.append(
        f"<h1>Visio shots {html.escape(manifest['run'])}</h1><pre>{html.escape(_summary(manifest).split(chr(10) + '## ')[0])}</pre>"
    )
    for stem, case in manifest["cases"].items():
        flag = " <span class='stale'>stale on open</span>" if case["stale_on_open"] else ""
        parts.append(f"<h2>{html.escape(stem)}{flag}</h2><p>{html.escape(case['line'])}</p><table><tr><td></td>")
        parts += [f"<td>{variant}</td>" for variant in _VARIANTS]
        parts.append("</tr>")
        for state in _STATES:
            parts.append(f"<tr><td>{_STATE_WORDS[state]}</td>")
            for variant in _VARIANTS:
                png = images.get(variant, {}).get(stem, {}).get(state)
                cell = f"<img src='data:image/png;base64,{base64.b64encode(png).decode('ascii')}'>" if png else "-"
                parts.append(f"<td>{cell}</td>")
            parts.append("</tr>")
        parts.append("</table>")
        for heading, found in case["findings"].items():
            if found:
                parts.append(
                    f"<p>{html.escape(heading)}</p><ul>" + "".join(f"<li>{html.escape(f)}</li>" for f in found) + "</ul>"
                )
    return "".join(parts)


def _record_run(
    store: Path,
    identity: dict,
    lines: dict[str, str],
    shots: dict[str, dict[str, dict]],
    *,
    build_errors: dict[str, dict[str, str]],
) -> dict:
    """Write one run into `store`: its manifest, summary and SVGs (committed), its PNGs and report (local); the manifest."""
    cases: dict[str, dict] = {}
    images: dict[str, dict[str, dict[str, bytes]]] = {}
    for stem, line in lines.items():
        stored: dict[str, dict] = {}
        for variant in _VARIANTS:
            shot = shots.get(variant, {}).get(stem)
            if shot is None:
                continue
            if "error" in shot:
                stored[variant] = {"error": shot["error"]}
                continue
            stored[variant] = {
                state: {
                    "svg": _put(store / "objects", _normalise_svg(shot[state]["svg"]).encode("utf-8"), ".svg"),
                    "png": _put(store / "local" / "png", shot[state]["png"], ".png"),
                }
                for state in _STATES
            }
            images.setdefault(variant, {})[stem] = {state: shot[state]["png"] for state in _STATES}
        found = _findings(shots, stem)
        cases[stem] = {"line": line, "shots": stored, "findings": found, "stale_on_open": bool(found[_STALE])}
    manifest = {**identity, "build_errors": build_errors, "cases": cases}

    run_dir = store / "runs" / identity["run"]
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (run_dir / "summary.md").write_text(_summary(manifest), encoding="utf-8")
    local = store / "local" / identity["run"]
    local.mkdir(parents=True, exist_ok=True)
    (local / "report.html").write_text(_report(manifest, images), encoding="utf-8")
    entry = {key: identity[key] for key in ("run", "created", "commit", "branch", "dirty", "against")} | {
        "cases": len(cases),
        "stale_on_open": [stem for stem, case in cases.items() if case["stale_on_open"]],
    }
    with (store / "index.jsonl").open("a", encoding="utf-8") as index:
        index.write(json.dumps(entry) + "\n")
    return manifest


def _manifest(store: Path, run: str) -> dict:
    return json.loads((store / "runs" / run / "manifest.json").read_text(encoding="utf-8"))


def _diff_runs(store: Path, first: str, second: str) -> list[str]:
    """Each case whose candidate verdict or drawing differs between two recorded runs, with what changed."""
    a, b = _manifest(store, first)["cases"], _manifest(store, second)["cases"]
    lines: list[str] = []
    for stem in sorted(a.keys() | b.keys()):
        if stem not in b or stem not in a:
            lines.append(f"{stem}: only in {first if stem in a else second}")
            continue
        was, now = a[stem], b[stem]
        header = []
        if was["stale_on_open"] != now["stale_on_open"]:
            stale, fresh = (first, second) if was["stale_on_open"] else (second, first)
            header.append(f"{stem}: stale on open in {stale}, not in {fresh}")
        details = []
        old_shots, new_shots = was["shots"].get("candidate", {}), now["shots"].get("candidate", {})
        for state in _STATES:
            old, new = old_shots.get(state), new_shots.get(state)
            if old is None or new is None:
                if old != new:
                    details.append(f"  {_STATE_WORDS[state]}: drawn in only one run")
                continue
            if old["svg"] != new["svg"]:
                changes = _diff_svgs(_svg_object(store, old["svg"]), _svg_object(store, new["svg"]))
                details += [f"  {_STATE_WORDS[state]}: {change}" for change in changes]
        if details and not header:
            header.append(f"{stem}: the candidate is drawn differently")
        lines += header + details
    return lines


# --- commands -----------------------------------------------------------------------


def _identity(run_id: str, created: str, against: dict | None, visio: dict, dpi: int) -> dict:
    commit = _git(_REPO, "rev-parse", "HEAD")
    return {
        "run": run_id,
        "created": created,
        "commit": commit,
        "branch": _git(_REPO, "branch", "--show-current") or "(detached)",
        "dirty": bool(_git(_REPO, "status", "--porcelain", "--", "src", "tools", "tests")),
        "against": against,
        "visio": visio,
        "dpi": dpi,
    }


def _command_run(builder: Path, against: str | None, store: Path, dpi: int) -> int:
    sys.path.insert(0, str(_TOOLS))
    import visio_verify

    now = datetime.datetime.now(datetime.timezone.utc)
    with tempfile.TemporaryDirectory(prefix="visio-shots-") as scratch:
        work = Path(scratch)
        candidate = work / "candidate"
        errors = {"candidate": _build(builder, _REPO / "src", candidate)}
        ref_info, ref_stems = None, set()
        if against:
            ref_src, commit = _export_library(_REPO, against, work / "ref-library")
            errors["ref"] = _build(builder, ref_src, work / "ref")
            ref_info = {"ref": against, "commit": commit}
            ref_stems = {case.stem for case in _read_cases(work / "ref")}
        cases = _read_cases(candidate)
        if not cases:
            print(f"{builder.name} built no cases: {errors['candidate']}", file=sys.stderr)
            return 2
        jobs = []
        for case in cases:
            before = candidate / f"{case.stem}.before.vsdx"
            if before.exists():
                jobs.append(("before", case, before))
            if case.stem in ref_stems:
                jobs.append(("ref", case, work / "ref" / f"{case.stem}.vsdx"))
            jobs.append(("candidate", case, candidate / f"{case.stem}.vsdx"))
        try:
            visio, shots = _shoot(jobs, dpi, work / "shots")
        except visio_verify.VisioUnavailable as error:
            print(f"Visio is not usable from here: {error}", file=sys.stderr)
            return 2
    run_id = f"{now:%Y%m%dT%H%M%SZ}_{_git(_REPO, 'rev-parse', '--short=7', 'HEAD')}"
    identity = _identity(run_id, now.isoformat(timespec="seconds"), ref_info, visio, dpi)
    manifest = _record_run(store, identity, {case.stem: case.line for case in cases}, shots, build_errors=errors)
    print(_summary(manifest).split("\n## ")[0])
    print(f"recorded {store / 'runs' / run_id}; images in {store / 'local' / run_id / 'report.html'}")
    return 1 if any(case["stale_on_open"] for case in manifest["cases"].values()) else 0


def main(argv: list[str] | None = None) -> int:
    """Run the harness; 0 when no candidate is stale on open, 1 when one is, 2 when it could not run."""
    parser = argparse.ArgumentParser(prog="visio_shots.py", description=__doc__.split("\n\n")[0])
    commands = parser.add_subparsers(dest="command", required=True)
    run = commands.add_parser("run", help="build, photograph and record the case set")
    run.add_argument("--against", help="a git ref whose library builds the comparison column, e.g. main")
    run.add_argument("--builder", type=Path, default=_BUILDER, help="the case module (default: tools/writes_land_cases.py)")
    run.add_argument("--store", type=Path, default=_STORE, help="where runs are recorded (default: .hermes/visio-shots)")
    run.add_argument("--dpi", type=int, default=150, help="PNG resolution (default: 150)")
    diff = commands.add_parser("diff-runs", help="what changed between two recorded runs")
    diff.add_argument("first")
    diff.add_argument("second")
    diff.add_argument("--store", type=Path, default=_STORE)
    args = parser.parse_args(argv)

    if args.command == "diff-runs":
        lines = _diff_runs(args.store, args.first, args.second)
        print("\n".join(lines) if lines else f"no case is drawn differently between {args.first} and {args.second}")
        return 0
    try:
        return _command_run(args.builder.resolve(), args.against, args.store, args.dpi)
    except BuildFailed as error:
        print(error, file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
